### ISSUE TITLE
some SHC devices not recognized after upgrade (i.e. lights entities)

### ISSUE THREAD

**Issue by wsirhc** [tschamm/boschshc-hass#103]
After Re-Authorization of my SHC (see https://github.com/tschamm/boschshc-hass/issues/102), I've recognized, that  some SHC devices are not shown up on HA.
So all my light entities are gone as well as the smoke detection binary entity from twinguard. Others like switches, twinguard temperature or power plugs have been detected properly.
There are no errors or warnings in logs.
I am using the latest master branch of this repo (Manifest "version": "0.4.50) and boschshcpy 0.2.57.

Any Idea what could be the cause?

**Comment by tschamm** [comment]
Hey @wsirhc 
Twinguard never had a smoke detection binary (it’s not exposed from Bosch side).
The light entities are LEDVANCE Lights or hue? LEDVANCE is still added, while Hue lights are much better integrated via the Hue component.

**Comment by wsirhc** [comment]
> Hey @wsirhc Twinguard never had a smoke detection binary (it’s not exposed from Bosch side). The light entities are LEDVANCE Lights or hue? LEDVANCE is still added, while Hue lights are much better integrated via the Hue component.

I referred to "binary_sensor.smokedetectionsystem".
The light entities are all LEDVANCE.

**Comment by tschamm** [comment]
Sorry I was quiet for some while, just too busy ... For your issue with LEDVANCE lights, can you maybe send me a [rawscan](https://github.com/tschamm/boschshcpy#rawscans) of one of the devices your missing. In particular I'm looking for the `deviceModel`.

**Comment by wsirhc** [comment]
Hi Thomas, here the snippet of the rawscan you requested (Serials have been replaced):

    {
        "@type": "device",
        "rootDeviceId": "64-da-a0-03-55-30",
        "id": "hdm:ZigBee:0123456789abcdef",
        "deviceServiceIds": [
            "CommunicationQuality",
            "MultiLevelSwitch",
            "HSBColorActuator",
            "BinarySwitch"
        ],
        "manufacturer": "LEDVANCE",
        "roomId": "hz_2",
        "deviceModel": "LEDVANCE_LIGHT",
        "serial": "0123456789ABCFED",
        "profile": "GENERIC",
        "iconId": "icon_ledvance_light_strip",
        "name": "Farbstreifen",
        "status": "AVAILABLE",
        "childDeviceIds": [],
        "supportedProfiles": []
    },
   {
        "@type": "device",
        "rootDeviceId": "64-da-a0-03-55-30",
        "id": "hdm:ZigBee:0123456789abcdef",
        "deviceServiceIds": [
            "CommunicationQuality",
            "HSBColorActuator",
            "MultiLevelSwitch",
            "BinarySwitch"
        ],
        "manufacturer": "LEDVANCE",
        "roomId": "hz_5",
        "deviceModel": "LEDVANCE_LIGHT",
        "serial": "0123456789ABCFED",
        "profile": "GENERIC",
        "iconId": "icon_ledvance_gu10",
        "name": "Terrasse_RGBW",
        "status": "UNAVAILABLE",
        "childDeviceIds": [],
        "supportedProfiles": []
    },
    {
        "@type": "device",
        "rootDeviceId": "64-da-a0-03-55-30",
        "id": "hdm:ZigBee:0123456789abcdef",
        "deviceServiceIds": [
            "CommunicationQuality",
            "MultiLevelSwitch",
            "HSBColorActuator",
            "BinarySwitch"
        ],
        "manufacturer": "LEDVANCE",
        "roomId": "hz_8",
        "deviceModel": "LEDVANCE_LIGHT",
        "serial": "0123456789ABCFED",
        "profile": "GENERIC",
        "iconId": "icon_philips_hue_bulb_a19",
        "name": "Arbeitszimmerlampe",
        "status": "AVAILABLE",
        "childDeviceIds": [],
        "supportedProfiles": []
    },

**Comment by wsirhc** [comment]
After testing some API functions, I don't see any changes on Bosch API side for e.g. triggering devices.
Also the boschshcpy dependency seems to be working correctly, when trying to get devices by using boschshcpy.

To clarify my issue:
By Listing all scenarions directly (GET https://192.168.180.103:8444/smarthome/scenarios), I get 27 scenarios.
By listing all devices directly (GET https://192.168.0.1:8444/smarthome/devices), I get a bunch of device models:
  "deviceModel": "BBL"
  "deviceModel": "BSM"
  "deviceModel": "HUE_BRIDGE_MANAGER"
  "deviceModel": "HUE_LIGHT_ROOM_CONTROL"
  "deviceModel": "INTRUSION_DETECTION_SYSTEM"
  "deviceModel": "LEDVANCE_LIGHT"
  "deviceModel": "MD"
  "deviceModel": "MULTISWITCH"
  "deviceModel": "PLUG_COMPACT"
  "deviceModel": "PRESENCE_SIMULATION_SERVICE"
  "deviceModel": "PSM"
  "deviceModel": "SMOKE_DETECTION_SYSTEM"
  "deviceModel": "SWD"
  "deviceModel": "TWINGUARD"
  "deviceModel": "VENTILATION_SERVICE"
  "deviceModel": "WRC2"


But on HA, there are no Scenarios and these device models listed: 
  SmartHomeController
  SWD
  BBL
  BSM
  MD
  PLUG_COMPACT
  PSM
  SmartHomeController
  TWINGUARD
  WRC2

So devices like LEDVANCE_LIGHT and all scenarios are missing. Even in Debug Log there is nothing that could lead to missing/incompatible devices or scenarios.

**Comment by wsirhc** [comment]
Found the issue...
It was a missing read permission on a custom component subfolder...
Now everything shows up as it should.
Sorry for the inconvenience!
