### ISSUE TITLE
Shutter controls not being recognized

### ISSUE THREAD

**Issue by Biggim22** [tschamm/boschshc-hass#105]
Hi there,

I've been using HA Integration of Bosch Smart Home with great pleasure and it's been working flawlessly and perfectly for water detection sensors, smoke detection sensors as well as for all of my heating thermostats.
However, none of my shutter and light contacts "Bosch Licht-/Rollladensteuerung II" are being recognized in Home Assistant.
Is there a manual way to integrate them maybe?

Thanks for your help, highly appreciated!
Cheers, Max

**Comment by tschamm** [comment]
Which version of that component are you using? The current version of this component is having the support.

**Comment by Biggim22** [comment]
Hi,

thank you for the quick reply.
Today I included another one of these shutter and light contacts to my system, that's where I first noticed that none of my three contacts are being recognized in HA.

Here's my current setup:

**Bosch Smart Home System**

I'm using the "Bosch Licht-/ Rollladensteuerung II" --> https://www.bosch-smarthome.com/de/de/produkte/geraete/licht-rollladensteuerung/
As a Hub I'm using the "Bosch Smart Home Controller II" --> https://www.bosch-smarthome.com/de/de/produkte/geraete/smart-home-controller/

I have 20 connected devices to this Hub, in HA it's only 17.


**Home Assitant**
Home Assitant OS on a Oracle VM on Win10

Home Assistant 2023.8.2
Supervisor 2023.08.1
Operating System 10.4
Frontend 20230802.0 - latest

Bosch SHC Integration is updated to the latest version.

**Comment by Biggim22** [comment]
sorry for closing and reopening - I misclicked :/

**Comment by tschamm** [comment]
I assume you have not installed the custom component but the default component. Only the custom component allows the integration of the shutter controls II

**Comment by Biggim22** [comment]
Thank you very much!

Using the custom component works very nice

I wasn't even aware that there are different builds / installs available.
