### ISSUE TITLE
Missing text in translation - "Last motion detected"

### ISSUE THREAD

**Issue by misa1515** [tschamm/boschshc-hass#110]
Missing text in translation - "Last motion detected" - you can see it in attached screenshot.
Thank you in advance for update.
![1695036620093_Bosch-LastMotionDetected](https://github.com/tschamm/boschshc-hass/assets/61636045/bf55cd03-d83f-4a9c-86be-534a127696a8)

**Comment by tschamm** [comment]
Should be solved, thanks to your contribution.
