### ISSUE TITLE
Shutter Control 2 sunblind

### ISSUE THREAD

**Issue by Schopenhauer178** [tschamm/boschshc-hass#111]
Hi, I am using the shutter control 2 to control my sunblind. Therefore it is set to the sunblind mode in the Bosch app. Unfortunately it doesn't show up in HA. Since I am using a large number of Bosch SHC components i suppose it is not supported yet (I reloaded the component already)?!  Would it be possible to integrate it?

Thanks for this great component and best greetings!

**Comment by tschamm** [comment]
hi @Schopenhauer178,
I guess you are referring to the Blinds control via the Micromodule. Actually there is support for this already, what version of the custom component are you using?

**Comment by Schopenhauer178** [comment]
Hi, great it is working with 4.62 now! Thanks a lot,

Best!
