### ISSUE TITLE
Bosch Universal Switch 2 not available

### ISSUE THREAD

**Issue by AlexW75** [tschamm/boschshc-hass#112]
Logger: boschshcpy
Source: /usr/local/lib/python3.11/site-packages/boschshcpy/session.py:213
First occurred: 11:01:41 (1 occurrences)
Last logged: 11:01:41

Error in polling thread: 'LOWER_RIGHT_BUTTON' is not a valid KeypadService.KeyState. Waiting 15 seconds.

After this message the switch becomes "unavailabe".
Occurs 1 time per day and requires a restart to get the switch back.

**Comment by tschamm** [comment]
Hi @AlexW75 
thanks for reporting. I was already wondering why the Universal Switch 2 is not working as expected. I guess that's the problem.
If added the missing keytypes now. It is still not perfect, it would be better to differentiate between the two device versions.
Can you check whether the button works in the latest update on master (6671e8b)?

**Comment by AlexW75** [comment]
Yes, can do a test today … will do 2 Tests

1.) Test if Error is gone when pressing buttons.
2.) Create an automation and try to get the press event.

Anything else I can do?

**Comment by AlexW75** [comment]
... ok have done the Tests:

1.) ERROR is gone - events are fired corretly.
Bosch SHC 'PRESS_LONG' click event for BSchalter Büro button 'UPPER_LEFT_BUTTON' was fired.
Bosch SHC 'PRESS_SHORT' click event for BSchalter Büro button 'UPPER_LEFT_BUTTON' was fired.
Bosch SHC 'PRESS_SHORT' click event for BSchalter Büro button 'LOWER_LEFT_BUTTON' was fired.

2.) When creating an automation the switch still have only a battery state.
I am quite new to HA ... however i have read in the docu that it is a possible to directly trigger on the event.
My question now is how I can tigger on the event - a code exapmle would help a lot.

**Comment by AlexW75** [comment]
There is one more problem...

Seems to that the button releases are not implemented yet.

Logger: custom_components.bosch_shc
Source: custom_components/bosch_shc/__init__.py:244
Integration: Bosch SHC (documentation, issues)
First occurred: 13:45:21 (1 occurrences)
Last logged: 13:45:21

Switch input event PRESS_LONG_RELEASED for device BSchalter Büro is not supported, please open issue

**Comment by tschamm** [comment]
And that is happening with the current master (not the lastest release)?

**Comment by AlexW75** [comment]
Yes, I took the changes of your Master to my installation.

**Comment by AlexW75** [comment]
Working now on your MASTER. No Warnings ... everything fine.
Bosch SHC 'PRESS_LONG_RELEASED' click event for BSchalter Büro button 'LOWER_LEFT_BUTTON' was fired.

**Comment by tschamm** [comment]
Ok, I will release it on Tuesday when I'm back from the one weekend 😉

**Comment by tschamm** [comment]
Release published.

**Comment by COLT9001** [comment]
Hi,
i have already installed the Version 0.4.6.3 in october but i have still the same problem.
I can not add a event, only battery status is avaliable for automations........


![bosch_1](https://github.com/tschamm/boschshc-hass/assets/120904667/4c1f22c8-86fe-40ee-8cb6-420d61c7fa44)
![bosch_2](https://github.com/tschamm/boschshc-hass/assets/120904667/0ea31dca-3944-4ffa-bf73-4eb50a8e47ea)

**Comment by tschamm** [comment]
I think I finally found that issue, you can test the current master.

**Comment by COLT9001** [comment]
Hi,

 

ich kann leider das Master im HACS nicht installieren. Er nimmt immer die alte Version 0.4.68

Die 0.4.69 taucht ja auch nicht auf sondern nur Master….. weiß nicht ob Hacs generell ein Problem damit hat?!?

 



 

Mit freundlichen Grüßen / Best regards

 

Andreas Sievers

 

Von: Thomas Schamm ***@***.***> 
Gesendet: Sonntag, 26. November 2023 20:41
An: tschamm/boschshc-hass ***@***.***>
Cc: COLT9001 ***@***.***>; Comment ***@***.***>
Betreff: Re: [tschamm/boschshc-hass] Bosch Universal Switch 2 not available (Issue #112)

 

I think I finally found that issue, you can test the current master.
