### ISSUE TITLE
Status of Actuator/Motor - Wall Thermostat Gen2

### ISSUE THREAD

**Issue by IT-Ludwig** [tschamm/boschshc-hass#116]
Hi,

Is it possible to get the status of the engine. Whether electricity flows or not. Is it possible to do this with a switch, on or off.

Thx

**Comment by tschamm** [comment]
No, API does not expose such function.

**Comment by IT-Ludwig** [comment]
Die API bietet doch die funktionierende den Status des Stellmotors abzufragen.
https://local.apidocs.bosch-smarthome.com/#/States/get_devices__deviceId__services_ValveTappet_state

Unter Services beim Raumthermostat 2
