### ISSUE TITLE
Events?

### ISSUE THREAD

**Issue by dolodobendan** [tschamm/boschshc-hass#118]
Hi,

Philips has event entities for their switches for some time now:

![image](https://github.com/tschamm/boschshc-hass/assets/37902856/e57c0646-8d16-4671-ab69-9b568d2c5729)

Would this be possible with [boschshc-hass](https://github.com/tschamm/boschshc-hass), too?

Thank you

**Comment by tschamm** [comment]
I already looked into it after the event entities have been released as new feature, but stopped I missed some implementation details. I plan to integrate this in one of the next releases.

**Comment by tschamm** [comment]
The current master adds support for the event Platform. Careful, it's a breaking change: The former `bosch_shc.event` will not be triggered for UniversalSwitches and Scenarios anymore. So you have to change automations.
If you want to test it and give feedback, I would be happy.

**Comment by tschamm** [comment]
The current release prevents the change to break existings systems, both the event platform as well as `bosch_shc.event` triggers can be used.

**Comment by dolodobendan** [comment]
> The current master adds support for the event Platform. Careful, it's a breaking change: The former `bosch_shc.event` will not be triggered for UniversalSwitches and Scenarios anymore. So you have to change automations. If you want to test it and give feedback, I would be happy.

Sure thing, how can I help?

**Comment by tschamm** [comment]
Is it working as expected?

**Comment by dolodobendan** [comment]
Nothing broken here. I used Device/Trigger "'LOWER_BUTTON' PRESS_SHORT" (etc.) as triggers in my automation and it still works. Thank you!

**Comment by Deniz66** [comment]
> Nothing broken here. I used Device/Trigger "'LOWER_BUTTON' PRESS_SHORT" (etc.) as triggers in my automation and it still works. Thank you!

Could you wirte an example please how to use the button event short press  from the "tür/fensterkontakt 2" to trigger an automatisation

**Comment by tschamm** [comment]
Bosch does not expose the button event via the API 😕. However you can create a scenario without any action in the Smart Home App and trigger that via the button. You can listen in HA to that scenario.
