### ISSUE TITLE
HA - NodeRed - Bosch SHC - Kommunikationsproblem

### ISSUE THREAD

**Issue by Brandy2588** [tschamm/boschshc-hass#119]
Hallo Zusammen,

ich bin ganz neu hier und versuche mich gerade etwas mit HA und meinem bestehenden Bosch SHC. Ich konnte den Bosch Controller 1 ohne Probleme mit HA verbinden. Gerne würde ich nun mit NodeRed ein paar spezielle Funktionen erstellen. Mein einziges Problem aktuell ist, dass ich in NodeRed keine Kommunikation zum Bosch SHC Controller aufbauen kann. Hier kommt immer folgender LOG
-------------------------------------------
}
BshbError: [ERROR] call to BSHC failed with HTTP status=401
    at PairingClient.handleError (/config/node-red/node_modules/bosch-smart-home-bridge/dist/api/abstract-bshc-client.js:186:32)
    at IncomingMessage.<anonymous> (/config/node-red/node_modules/bosch-smart-home-bridge/dist/api/abstract-bshc-client.js:149:34)
    at IncomingMessage.emit (node:events:529:35)
    at endReadableNT (node:internal/streams/readable:1368:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errorType: 0,
  [cause]: undefined
}
------------------------------------------------------------
Hab schon mehrere Versuche mit andere Einstellungen vorgenommen, aber leider alle erfolglos.
Würde mich freuen, wenn mir jemand helfen könnte.

Wenn möglich mit etwas detaillierterer  Vorgehensweise, da ich aus der Automatisierung komme und in den IT-Skills nicht ganz so umgangssicher bin.

Vielen Dank

**Comment by armin-gh** [comment]
I guess this should be a question to the project providing the Bosch SHC module for NodeRed.
Based on the error you might use an outdated version of this module, if has to support the latest API-Version for the controller ( which the Bosch SHC component does support, hence no error in the connection from HA)

**Comment by tschamm** [comment]
Please report here: https://github.com/hxmelab/node-red-contrib-bosch-shc
