### ISSUE TITLE
Use external reference temp for TRV2

### ISSUE THREAD

**Issue by H4rryK4ne** [tschamm/boschshc-hass#121]
Hi,

as already asked in the community: https://community.home-assistant.io/t/bosch-thermostat-2-external-reference-temperature/641327

Do you have an idea, how I can use the temperature of an external thermostat instead of the internal one of the TRV?

Best regards,
Martin

**Comment by tschamm** [comment]
This won't be possible, as you cannot override the internal TRV sensor. 
You can however control the target setpoint of the TRV via an automation.
