### ISSUE TITLE
Four out of six motion sensors show a constant brightness value

### ISSUE THREAD

**Issue by moritzmaier84** [tschamm/boschshc-hass#122]
![tschamm](https://github.com/tschamm/boschshc-hass/assets/143726388/9339db63-5293-42dd-b8a2-1823bf0ea070)

I've integrated six Bosch motion sensors via 'tschamm.' As seen in the picture, two of them display differentiated correct brightness values, while the other four show a constant value that never changes. I don't understand this because obviously, I've integrated everything correctly since it works on some devices, and everything else runs perfectly with Bosch.
I also find it unlikely that these four devices are all defective.

Could there be an error in the integration here? What else could be the cause? Without the brightness values, I can't integrate meaningful motion lighting. It has always worked well in the Bosch app with all six devices, but I want to implement it in Home Assistant.

Thx in advance!

**Comment by tschamm** [comment]
That is interesting! I only have one motion sensor, and that is reporting an almost constant brightness value over several days. I was just assuming it cannot do better, but the 2 sensors you are describing are working much more precisely. Are you sure that the brightness values in the Bosch app are reported correctly and are up to date?

**Comment by moritzmaier84** [comment]
I tested with the flashlight in front of the sensor. Neither in HA nor in the Bosch app do the brightness values of the four sensors change.
I don't understand this. Are there two different series?
Or does it have something to do with the battery?
It would be very interesting because the way the two good sensors work, they are really perfect.

**Comment by tschamm** [comment]
You may ask your question in that [forum](https://github.com/BoschSmartHome/bosch-shc-api-docs/issues), however I guess it is not directly related with the API, but more a bug in the sensor. So if the sensor is still relatively new, you can ask via the official support channel for further information.

**Comment by moritzmaier84** [comment]
Just for information: I tried everything. Battery-Changes, Reset and re-adding in Bosch... But the four devices won't change their values.
I also tried to add it in HA via ZHA but it stucked with saying "Starting Interview" (I don't know why, never had this problem) so I could not test, if the sensor would bring better values there. That would have been interesting, though.
