### ISSUE TITLE
integration Dimmer

### ISSUE THREAD

**Issue by G3usen** [tschamm/boschshc-hass#123]
Hi, 
I'd like to use the Bosch Dimmer inside home assistant. 
Would an integration be possible? 

Best regards 
Robin

**Comment by G3usen** [comment]
https://www.bosch-smarthome.com/de/de/produkte/geraete/dimmer/

**Comment by tschamm** [comment]
You need to make a rawscan of the device. see documentation in `boschshcpy`.

**Comment by G3usen** [comment]
THX - there you are:

    {
        "@type": "device",
        "rootDeviceId": "64-da-a0-02-e1-6f",
        "id": "hdm:ZigBee:60b647fffe0a2ff3",
        "deviceServiceIds": [
            "CommunicationQuality",
            "PowerSwitch",
            "ChildProtection",
            "ElectricalFaults",
            "MultiLevelSwitch",
            "DimmerConfiguration",
            "SwitchConfiguration"
        ],
        "manufacturer": "BOSCH",
        "roomId": "hz_3",
        "deviceModel": "MICROMODULE_DIMMER",
        "serial": "60B647FFFE0A2FF3",
        "profile": "GENERIC",
        "iconId": "ip_lamp_ceiling_oval",
        "name": "Kronleuchter",
        "status": "AVAILABLE",
        "childDeviceIds": [],
        "supportedProfiles": []
    },

**Comment by tschamm** [comment]
I would need the services of that device, too.

**Comment by G3usen** [comment]
Hi Thomas, 
Noob question regarding boschcpy - how do I get them?

**Comment by G3usen** [comment]
Hi Thomas,

thx for your quick repsonse :)

[
    {
        "@type": "DeviceServiceData",
        "id": "SwitchConfiguration",
        "deviceId": "hdm:ZigBee:60b647fffe0a2ff3",
        "state": {
            "@type": "SwitchConfigurationState",
            "switchType": "PUSHBUTTON",
            "swapInputs": false
        },
        "path": "/devices/hdm:ZigBee:60b647fffe0a2ff3/services/SwitchConfiguration"
    },
    {
        "@type": "DeviceServiceData",
        "id": "ElectricalFaults",
        "deviceId": "hdm:ZigBee:60b647fffe0a2ff3",
        "path": "/devices/hdm:ZigBee:60b647fffe0a2ff3/services/ElectricalFaults"
    },
    {
        "@type": "DeviceServiceData",
        "id": "ChildProtection",
        "deviceId": "hdm:ZigBee:60b647fffe0a2ff3",
        "state": {
            "@type": "ChildProtectionState",
            "childLockActive": false
        },
        "path": "/devices/hdm:ZigBee:60b647fffe0a2ff3/services/ChildProtection"
    },
    {
        "@type": "DeviceServiceData",
        "id": "CommunicationQuality",
        "deviceId": "hdm:ZigBee:60b647fffe0a2ff3",
        "state": {
            "@type": "communicationQualityState",
            "quality": "GOOD"
        },
        "path": "/devices/hdm:ZigBee:60b647fffe0a2ff3/services/CommunicationQuality"
    },
   {
        "@type": "DeviceServiceData",
        "id": "DimmerConfiguration",
        "deviceId": "hdm:ZigBee:60b647fffe0a2ff3",
        "state": {
            "@type": "DimmerConfigurationState",
            "edgePhaseControlMode": "TRAILING",
            "brightnessRange": {
                "minBrightness": 8,
                "maxBrightness": 35
            },
            "dimmingSpeed": 5
        },
        "operations": [
            "previewMaxBrightness",
            "previewMinBrightness"
        ],
        "path": "/devices/hdm:ZigBee:60b647fffe0a2ff3/services/DimmerConfiguration"
    },
    {
        "@type": "DeviceServiceData",
        "id": "PowerSwitch",
        "deviceId": "hdm:ZigBee:60b647fffe0a2ff3",
        "state": {
            "@type": "powerSwitchState",
            "switchState": "OFF",
            "automaticPowerOffTime": 0
        },
        "path": "/devices/hdm:ZigBee:60b647fffe0a2ff3/services/PowerSwitch"
    },
    {
        "@type": "DeviceServiceData",
        "id": "MultiLevelSwitch",
        "deviceId": "hdm:ZigBee:60b647fffe0a2ff3",
        "state": {
            "@type": "multiLevelSwitchState",
            "level": 30
        },
        "path": "/devices/hdm:ZigBee:60b647fffe0a2ff3/services/MultiLevelSwitch"
                                                                                     }
]

**Comment by JohnFCreep** [comment]
Hey, is there any update and maybe a beta I could try?

**Comment by jumlu** [comment]
I created a pull request for boschshcpy. Once this is approved, I will create a pull request to add it to HA as well.

**Comment by jumlu** [comment]
Pull request for boschshc-hass is created. The dimmer is already working at my end. Greetings.

**Comment by JohnFCreep** [comment]
My hero. It works! Now my christmas gift is useable 😄

**Comment by G3usen** [comment]
Thx a lot :)

**Comment by tschamm** [comment]
Fixed, may thanks to @jumlu for providing the code and testing!
