### ISSUE TITLE
Vorschlag: Zustände in HA einbinden  (Virtueller Schalter)

### ISSUE THREAD

**Issue by Matze89x** [tschamm/boschshc-hass#124]
Hallo an euch, endlich besteht die Möglichkeit (nach App-Update heute) ein virtueller Schalter in der Bosch-Smart-Home-Welt zu hinterlegen. Damit würde sich eine Schnittstelle zwischen BSH~HA ergeben.

Ich würde mich sehr über den Schalter in Home Assistant freuen, um sozusagen fehlende Funktionen in BSH zu senden/lesen und umgekehrt.

![image](https://github.com/tschamm/boschshc-hass/assets/75788739/a97f5846-a7d8-460a-8258-a70ef2e6c313)![image](https://github.com/tschamm/boschshc-hass/assets/75788739/b965f0ea-18ff-4bcf-94b3-e526f20993fd)![image](https://github.com/tschamm/boschshc-hass/assets/75788739/c3b47592-d4fd-4e63-b00d-ecf6053a7a83)

**Comment by tschamm** [comment]
Also Kopplung der Schalter auf HA und SmartHome Seite? Muss ich prüfen, inwiefern der Schaltet über die API angesteuert werden kann.
