### ISSUE TITLE
Vavle Position of Room Climate Control

### ISSUE THREAD

**Issue by JanZimmer** [tschamm/boschshc-hass#13]
In the BOSCH SmartHome App, you can finde the Valve Position (Ventilstellung) of room climate controls as a separate information.

Is this information also available via this integration, and if so, how is it called/do I find it.

Thanks for the great work!

**Comment by tschamm** [comment]
The valve tappet position is an attribute of each thermostat device, not of the room climate control. It’s already available in the current version.

**Comment by JanZimmer** [comment]
Awsome, I then have to update my currently running instance.
