### ISSUE TITLE
bosch_shc.event not working any more on US2

### ISSUE THREAD

**Issue by AlexW75** [tschamm/boschshc-hass#133]
Hello Tschamm,

I've recently updated to the latest version, and since then, I'm unable to detect the bosch_shc.event from my Bosch Universal Switches 2.

Here's the setup I'm using:
trigger:
  - platform: event
    event_type: bosch_shc.event
    event_data:
      device_id: XXX
      id: XXX
      event_subtype: UPPER_LEFT_BUTTON
      event_type: PRESS_SHORT

However, when I try to monitor the bosch_shc.event in the developer tools, the event doesn't seem to be triggered.

Best regards,
Alex

**Comment by tschamm** [comment]
@AlexW75 can you test this again. I don't have the Switch 2, but with the Switch 1, everything works as expected. If the error is still occuring, can you look into the log if there are error messages related to that issue?

**Comment by AlexW75** [comment]
With your newest update the problem is solved.

Thanks!
