### ISSUE TITLE
Using Smokedetectors / Twinguards as a siren

### ISSUE THREAD

**Issue by moritzmaier84** [tschamm/boschshc-hass#134]
Is there any way to use the sirens from the devices via HA-service oder something like that?
I don't wanna use the Bosch Alarm Service because I have other triggers in Home-Assistant so I builded an alarm system right there in HA. But if they are triggered, there is no way to use the sirens of my Bosch devices for that...

**Comment by tschamm** [comment]
This is exposed via the bosch API. Please file a bug report [here](https://github.com/BoschSmartHome/bosch-shc-api-docs/issues)
