### ISSUE TITLE
Certificate in wrong folder after backup /brestore migration from core to HAOS

### ISSUE THREAD

**Issue by Matthias-Beck** [tschamm/boschshc-hass#138]
Hi guys,

I have migrated my HA from core to HAOS running on a x86_64.
I did the migration with backup restore.

The boschshc integration is not starting after the restore. From the protocols I can see, it still searches the pem file at /home/homeassistant/.homeassistant/....
But on HAOS the folders are different.

I already deleted the integration and recreated it again, which did not solve the issue.

In which file is the path to the pem file stored?

**Comment by tschamm** [comment]
The certificate should be here: `config_path/bosch_shc`
