### ISSUE TITLE
Device names of Room Climate Controls is always "-RoomClimateControl-"

### ISSUE THREAD

**Issue by JanZimmer** [tschamm/boschshc-hass#14]
After updating to the most recent version of boschshc-hass and boschshcpy and runnint a clean integration setup, Thermostats are detected as both "Heizung" and "Room Climate Control" (as before), where Heizung is the sensor and Room Climate Control is the actor. 

However, the name of the Room Climate Controls is now always detected with a device name of "-RoomClimateControl-", which makes it hard to distinguish (entity name is correct).  Is this "wanted" behavior or a bug?

Thanks

**Comment by tschamm** [comment]
Actually that was a bug. I changed the name handling recently, as it happend that the first platform loaded defined the entity name as well as the device name. This is more explicit now.
Thanks for reporting.
