### ISSUE TITLE
deprecated constant which will be removed in HA Core 2025.1

### ISSUE THREAD

**Issue by Regnator** [tschamm/boschshc-hass#140]
Hello,

I got several warnings in the current 2024.1.0 update, that the following constants will be deprecated in 2025.1 : 

> POWER_WATT was used from bosch_shc, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPower.WATT instead, please create a bug report at https://github.com/tschamm/boschshc-hass/issues
> TEMP_CELSIUS was used from bosch_shc, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/tschamm/boschshc-hass/issues

> SUPPORT_ALARM_ARM_AWAY was used from bosch_shc, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.ARM_AWAY instead, please create a bug report at https://github.com/tschamm/boschshc-hass/issues
SUPPORT_ALARM_ARM_CUSTOM_BYPASS was used from bosch_shc, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.ARM_CUSTOM_BYPASS instead, please create a bug report at https://github.com/tschamm/boschshc-hass/issues
SUPPORT_ALARM_ARM_HOME was used from bosch_shc, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.ARM_HOME instead, please create a bug report at https://github.com/tschamm/boschshc-hass/issues

> HVAC_MODE_AUTO was used from bosch_shc, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.AUTO instead, please create a bug report at https://github.com/tschamm/boschshc-hass/issues
HVAC_MODE_HEAT was used from bosch_shc, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.HEAT instead, please create a bug report at https://github.com/tschamm/boschshc-hass/issues
HVAC_MODE_OFF was used from bosch_shc, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.OFF instead, please create a bug report at https://github.com/tschamm/boschshc-hass/issues
SUPPORT_PRESET_MODE was used from bosch_shc, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.PRESET_MODE instead, please create a bug report at https://github.com/tschamm/boschshc-hass/issues
SUPPORT_TARGET_TEMPERATURE was used from bosch_shc, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_TEMPERATURE instead, please create a bug report at https://github.com/tschamm/boschshc-hass/issues

> SUPPORT_OPEN_TILT was used from bosch_shc, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.OPEN_TILT instead, please create a bug report at https://github.com/tschamm/boschshc-hass/issues
SUPPORT_SET_POSITION was used from bosch_shc, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.SET_POSITION instead, please create a bug report at https://github.com/tschamm/boschshc-hass/issues
SUPPORT_SET_TILT_POSITION was used from bosch_shc, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.SET_TILT_POSITION instead, please create a bug report at https://github.com/tschamm/boschshc-hass/issues
SUPPORT_STOP was used from bosch_shc, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.STOP instead, please create a bug report at https://github.com/tschamm/boschshc-hass/issues
SUPPORT_STOP_TILT was used from bosch_shc, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.STOP_TILT instead, please create a bug report at https://github.com/tschamm/boschshc-hass/issues

> AutomationActionType was used from bosch_shc, this is a deprecated constant which will be removed in HA Core 2025.1. Use TriggerActionType instead, please create a bug report at https://github.com/tschamm/boschshc-hass/issues

**Comment by tschamm** [comment]
Fixed in 0.4.77
