### ISSUE TITLE
Feature Request: Add events for Button press on Window Contact II

### ISSUE THREAD

**Issue by borys-kupar** [tschamm/boschshc-hass#146]
Hey everyone, 

[Window Contact II](https://www.bosch-smarthome.com/uk/en/products/devices/doorwindow-contact/) has also a button, it can capture single and long press. You could use it in the Bosch app to set up an automation. It would be very helpful to have support for it in the Home Assistant too.

I am not sure the support is available in https://github.com/tschamm/boschshcpy, let me know if I should move this issue there.

**Comment by tschamm** [comment]
Problem is the button press is not available via API, only via Automations. However you can create an „empty“ scenario an react on HA side on triggers of that scenario.
