### ISSUE TITLE
How to Add Scenarios from Bosch SHC to Home Assistent

### ISSUE THREAD

**Issue by marcelbielmeier** [tschamm/boschshc-hass#148]
I dont know if this is the right place for something like that, 

How can I Add a Scenario origially from Bosch Controller and uns is like a Button in Home Assist? 

I found the boschshc trigger scenario but i have no Idea how to configure it. 

Can anybody help?

**Comment by tschamm** [comment]
You can use the scenario as a trigger in an automation. Either listen to events from `bosch_shc.event` or go to the SHC device page, then click the + symbol next to automations and you should be able to choose the scenario as a trigger.

**Comment by marcelbielmeier** [comment]
sorry i dont understand this. 

I will make a example: 

i want to shut down all my shutters with one click. 
in bosch shc i made a scene „all shutters down“. 
I can press the button in the bosch app. 

In HA i can create a butten „Close shutters“ and i can connet a service „dienst aufrufen“

i added two pictures: 

![IMG_2924](https://github.com/tschamm/boschshc-hass/assets/156211191/a4588d9a-38ce-4e8b-a6b2-e09882ba3e24)


![IMG_2923](https://github.com/tschamm/boschshc-hass/assets/156211191/7ba8dfd1-d4da-4fba-b8e7-30979bf927dd)

Maybe i understand it better when you support me in german. :)

**Comment by marcelbielmeier** [comment]
I dont understand what names i have to use und the fields shc name and scenario. 

I think that just this is my problem. :)

**Comment by tschamm** [comment]
You don't need to provide the SHC name, that is only necessary in case you have same Scenario names on two SHCs. The scenario name is actually the given name in the Bosch App. For example "Schlafen abdunkeln" should be a valid name.

**Comment by tschamm** [comment]
Is it working for you now?

**Comment by marcelbielmeier** [comment]
Yes! Thank you! Good Description.
