### ISSUE TITLE
Warning "Entity None" with 2024.1.2

### ISSUE THREAD

**Issue by lesgrebe** [tschamm/boschshc-hass#149]
Hello,

related to the post https://github.com/tschamm/boschshc-hass/issues/141 I updated to v0.4.78 (SHC Integration) an most of these "Entity None" warnings are gone but one warning is still appears after Hass restart:

Logger: homeassistant.components.light
Source: components/light/__init__.py:1194
Integration: Licht (documentation, issues)
First occurred: 16:27:38 (2 occurrences)
Last logged: 16:27:38

Entity None (<class 'custom_components.bosch_shc.light.LightSwitch'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <LightEntityFeature: 19> and color modes, please create a bug report at https://github.com/tschamm/boschshc-hass/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

Systeminformation:
![image](https://github.com/tschamm/boschshc-hass/assets/37287548/3138f125-4f52-4aa0-af1b-5d02f36e22cb)

Maybe there is a fix for this in a future update? Thx. a lot!

Regards
Michi

**Comment by smarthomefamilyverrips** [comment]
As this is a error related to a custom component the issue should not be posted here as is not related to HA core, like the message already told you post your issue here. https://github.com/tschamm/boschshc-hass/issues

**Comment by lesgrebe** [comment]
Hi,

fixed with update to 0.4.82!

Thanks a lot!
Regards
Michi
