### ISSUE TITLE
As long as boschshc-hass is not part of hass-core, support HACS 

### ISSUE THREAD

**Issue by JanZimmer** [tschamm/boschshc-hass#15]
It would be nice, if this custom component was available via HACS. This would made updates a lot easier :)

**Comment by tschamm** [comment]
@JanZimmer I digged through the HACS documentation and managed to have this CC at least available for HACS custom. I will try to have to repository added to HACS default.

**Comment by JanZimmer** [comment]
@tschamm works like a charm. Will updates via HACS also update boschshcpy now? (HASS is running as docker)
Also, the documentation might include the necessary information on how to install via HACS :)
Thanks!
