### ISSUE TITLE
MICROMODULE_RELAY only shows Child_Lock

### ISSUE THREAD

**Issue by danielpetrovic** [tschamm/boschshc-hass#150]
Most devices work ok, but the Smart Relay only shows Child_Lock option, nothing else.
The device type is: BMCT-RZ

It is configured as switch in on/off mode in the Bosch SHC app.
Within the Bosch app it works fine and HomeKit works fine as well.

**Comment by Salrok** [comment]
Yup, the same goes for me. 

and in https://github.com/tschamm/boschshc-hass/issues/113 and https://github.com/tschamm/boschshc-hass/issues/101

**Comment by tschamm** [comment]
Thats right, it's a duplicate.
