### ISSUE TITLE
Set Preset "eco"

### ISSUE THREAD

**Issue by androidwannabe** [tschamm/boschshc-hass#151]
Is there any way to set the "eco" preset on the thermostats vie home assistant?

"Eco" is the preset the Bosch controller selects when you open a window, if you have activated that feature in the app. Now, I would like to set different delays for different windows and doors, but in the Bosch app it is only possible to choose one value for all windows. 

When I select the "eco" preset in home assistant, nothing happens and it switches back to "none" after a moment. "Boost" is working fine though.

**Comment by MartinGoX** [comment]
Hi everyone
Quite funny, I just wanted to open the same/similar topic with the background to set 'Eco mode' in case our vacuum robot needs open doors for a longer time...

Kind regards

**Comment by tschamm** [comment]
I checked that. It seems the API is only reporting if the thermostat is in Eco mode, but Eco mode cannot be set via the API. You need to report a bug in the [bosch smart home repository](https://github.com/BoschSmartHome/bosch-shc-api-docs)
