### ISSUE TITLE
Fehlerhafte (deutsche) Entitäten werden nach Neustart angelegt

### ISSUE THREAD

**Issue by moritzmaier84** [tschamm/boschshc-hass#152]
Seit neustem werden bei mir bei Neustart von HA bei beinahe allen Bosch Geräten doppelte Entitäten angelegt. Diese haben dann einen deutschen Namen und auch die ID ist deutsch formuliert. Sie werden aber alle nicht gefunden und lassen sich händisch deshalb löschen.
Die "alten" englischen Entitäten sind auch noch da und funktionieren wie gewöhnlich.

Was ist da los? Woher kommt das auf einmal? Und wie kriege ich es weg? Es "versaut" mir das ganze System so.

Danke!
Moritz

**Comment by tschamm** [comment]
Can you send me the 
`core.entity_registry` from your `config/.storage` folder via PM in the HA community forum?
I did not do a rewrite of entities since a longer time. But maybe if you updated from a very old `boschshc_hass` version, this could be the reason.

**Comment by tschamm** [comment]
Is this issue still existing?

**Comment by moritzmaier84** [comment]
No - it was just gone some day. Sorry for forgetting to tell you!
