### ISSUE TITLE
With update 0.4.82 all Hue lights are also present in Bosch SHC

### ISSUE THREAD

**Issue by danielpetrovic** [tschamm/boschshc-hass#153]
With update 0.4.82 all my Hue lights were now also added to the Bosch SHC implementation.

Device type:
HUE_LIGHT

Is there a way to make this an option to enable/disable? As I already have my Hue Hub linked to Home Assistant which has more functions and entities. So now I have double entities for all my lights.

I have linked my Bosch and Hue hubs so the Bosch alarm system can work completely independent with the Hue Hub, when Home Assistant might be down.

**Comment by tschamm** [comment]
This was not intentional.

**Comment by tschamm** [comment]
You mean you have orphane devices now without entities in it? 
In case you feel comfortable with, make a backup of your `config/.storage/core.device_registry`, edit that file, all newly added devices should be near the end of the file.

**Comment by danielpetrovic** [comment]
> You mean you have orphane devices now without entities in it? In case you feel comfortable with, make a backup of your `config/.storage/core.device_registry`, edit that file, all newly added devices should be near the end of the file.

Yes, that’s exactly it.

Sadly they were not at the end of the file with 14192 lines. I did find them by searching for HUE_LIGHT so I could remove them safely, thanks.
