### ISSUE TITLE
Bosch Room Thermostate 2 dont shows battery state

### ISSUE THREAD

**Issue by AlexW75** [tschamm/boschshc-hass#157]
I have a small minor problem there is no way to show the battery status of Room Thermostate 2.

Would be really nice if the value is added to a future realease.

**Comment by tschamm** [comment]
It should be shown as a binary sensor.

**Comment by AlexW75** [comment]
In the case of my thermostats -
 Yes it works. In case of the room thermostat 2 there is no battery information.

**Comment by tschamm** [comment]
right, I can confirm. Should be fixed in release 0.4.85
