### ISSUE TITLE
Thermostat set_temperature not complete

### ISSUE THREAD

**Issue by jo-me** [tschamm/boschshc-hass#16]
According to the docs at https://www.home-assistant.io/integrations/climate/ 
the set_temperature call has an optional hvac_mode parameter which allows to change both the mode and the temperature with one call.

As far as I can see, this is not implemented in this component.

For comparison tado's set_temperature: https://github.com/home-assistant/core/blob/dev/homeassistant/components/tado/climate.py

**Comment by tschamm** [comment]
@jo-me I will have a look at this.

**Comment by tschamm** [comment]
@jo-me Fixed in 40ccc3292975668e83f911eec2f8de6bac5b58ab
