### ISSUE TITLE
climate.ClimateControl warning with >= 2024.2

### ISSUE THREAD

**Issue by Gloomyeye** [tschamm/boschshc-hass#161]
Hello,

The following warning occurs with the current beta version of home assistant 2024.2.0b3:

Logger: homeassistant.components.climate
Source: components/climate/__init__.py:357
Integration: Klima (documentation, issues)
First occurred: 11:18:44 (12 occurrences)
Last logged: 11:18:44

Entity None (<class 'custom_components.bosch_shc.climate.ClimateControl'>) implements HVACMode(s): auto, heat, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/tschamm/boschshc-hass/issues

**Comment by Matze89x** [comment]
Hello, if I understand correctly - are there problems with the update to 2024.2 in general?

or is it working as it will be released tonight.

**Comment by Gloomyeye** [comment]
For me, no errors so far. Only a warning is shown in the log.

**Comment by Gloomyeye** [comment]
The issue is still valid an is shown in 2024.4.b1.

**Comment by Gloomyeye** [comment]
Still valid also for 2024.5.b1.

**Comment by tschamm** [comment]
Should be fixed in latest release
