### ISSUE TITLE
Supporting Bosch CLIMATE 3000i controlled by HomeCom app?

### ISSUE THREAD

**Issue by alvarokrn** [tschamm/boschshc-hass#162]
Hi friend!

I wonder if you are planning to add support for devices like Bosch CLIMATE 3000i which are controlled by the HomeCom app and at least as far as I know it does not have any integration with HA.

Thanks in advance!

PS: There is a thread in the HA Community forum where a user commented something about it https://community.home-assistant.io/t/bosch-5000i-air-conditioning/367752/10

**Comment by tschamm** [comment]
This will not be supported, please look for the HomeCom integration.

**Comment by alvarokrn** [comment]
Which HomeCome Integration? Where?

**Comment by alvarokrn** [comment]
Looks like one year later, one developer (@serbanb11) has implemented what I was looking for: https://github.com/serbanb11/bosch-homecom-hass/
