### ISSUE TITLE
Ledvance RGBW are recognized as RGB-only

### ISSUE THREAD

**Issue by JanZimmer** [tschamm/boschshc-hass#17]
After restarting the home assistant, RGBW Ledvance lights are only detected as RGB.

(Another reason might be, that I temporarily tried to put them in a light group. Also, I'm not sure if it was detected as RGBW at all ... quite bad Issue description, sorry)

**Comment by tschamm** [comment]
I guess the light platform never did support RGBW. The SHC interface is limited to RGB color values. Can you describe what kind of parameter you are missing?

**Comment by JanZimmer** [comment]
So for RGBW, besides the option of setting RGB values, there is the option of setting the color (or white) temperature (I think they also call it hue). This will enable the W-LEDs in the bulb instead of "mixing" the color with the RGB-LEDs. 

(I had a quick look though your code, I think you even have the needed services implemented, maybe the Ledvance bulbs just return wrong available services via the API?)

**Comment by tschamm** [comment]
The two relevant services are `HueColorTemperature` and `HSBColorActuator`. For devices which support only HueColorTemperature, everything is fine. I'll have a look why the color temperature is not shown for devices which support both.
Thanks for reporting!

**Comment by tschamm** [comment]
@JanZimmer Can you confirm (e.g. via `postman`) that your RGBW device provides both services, `HueColorTemperature` as well as `HSBColorActuator`?

**Comment by JanZimmer** [comment]
@tschamm here you go:

**Comment by JanZimmer** [comment]
Also here ist the output for each of the services for documentation purposes:
```
[
    {
        "@type": "DeviceServiceData",
        "id": "BinarySwitch",
        "deviceId": "hdm:ZigBee:xxx",
        "state": {
            "@type": "binarySwitchState",
            "on": false
        },
        "path": "/devices/hdm:ZigBee:xxx/services/BinarySwitch"
    },
    {
        "@type": "DeviceServiceData",
        "id": "HSBColorActuator",
        "deviceId": "hdm:ZigBee:xxx",
        "state": {
            "@type": "colorState",
            "rgb": -12427,
            "gamut": "LEDVANCE_GAMUT_A",
            "colorTemperatureRange": {
                "minCt": 153,
                "maxCt": 526
            }
        },
        "path": "/devices/hdm:ZigBee:xxx/services/HSBColorActuator"
    },
    {
        "@type": "DeviceServiceData",
        "id": "CommunicationQuality",
        "deviceId": "hdm:ZigBee:xxx",
        "state": {
            "@type": "communicationQualityState",
            "quality": "UNKNOWN"
        },
        "path": "/devices/hdm:ZigBee:xxx/services/CommunicationQuality"
    },
    {
        "@type": "DeviceServiceData",
        "id": "MultiLevelSwitch",
        "deviceId": "hdm:ZigBee:xxx",
        "state": {
            "@type": "multiLevelSwitchState",
            "level": 100
        },
        "path": "/devices/hdm:ZigBee:xxx/services/MultiLevelSwitch"
    }
]
```

**Comment by tschamm** [comment]
@JanZimmer Light platform now supports color temp. I use the `HSBColorActuator` for setting the temperature, this should be fine as I guess the light hardware itself handles which type of LEDs are used. If the upstream issue you opened will be fixed, we can change behavior in the light platform.
Regards, Thomas

**Comment by JanZimmer** [comment]
@tschamm thanks.
So BOSCH does not consider supporting the HueColorTemperature Service in the future. Seems to be a bit more challenging, than I thought. Thanks anyways :) I might have a more detailed look into things in the future
