### ISSUE TITLE
Warning light (Ledvance devices) does not report a color mode, this will stop working in Home Assistant Core 2025.3

### ISSUE THREAD

**Issue by lesgrebe** [tschamm/boschshc-hass#172]
Hello,

Since HA update to 2024.3.0 everytime after turn on the light (Ledvance light bulbs and also Ledvance LED-Strips) a warning occurs in the logger. The integration and the light itself works without any problems (HACS Integration version 0.4.88).

Warning-Log (Screenshot):
![image](https://github.com/tschamm/boschshc-hass/assets/37287548/a0bbe4c0-ff7d-4751-ad99-714ccd658b33)

Warning-Log (Text):
Logger: homeassistant.components.light
Quelle: components/light/__init__.py:914
Integration: Licht (Dokumentation, Probleme)
Erstmals aufgetreten: 09:13:37 (1 Vorkommnisse)
Zuletzt protokolliert: 09:13:37

light.stehlampe (<class 'custom_components.bosch_shc.light.LightSwitch'>) does not report a color mode, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/tschamm/boschshc-hass/issues

System in use (Raspberry Pi 4 8GB):
![image](https://github.com/tschamm/boschshc-hass/assets/37287548/6dadc3b5-314d-4309-9713-261634a8d78e)

Maybe we get a fix in an future update - thx. a lot!

Regards
Michael

**Comment by lesgrebe** [comment]
Hi @tschamm !

The warning is still present in 2024.09.3, do you have any news on this?
Thanks!

Regards
Michi

**Comment by tschamm** [comment]
Can you check if the error is gone, and functionality is still ok. I did an update in version 0.4.91

**Comment by lesgrebe** [comment]
Hi!
Version 0.4.91 fixed it 👍🏽
Thank you!
