### ISSUE TITLE
Config flow not loading ("Invalid handler specified")

### ISSUE THREAD

**Issue by leonbittner** [tschamm/boschshc-hass#173]
Hi!

I am currently trying to install this integration, however my Bosch SHC (Gen 1) is not shown as automatically discoverd. If I try to add the integration manually, I get the following error message:

 The config flow could not be loaded: {"message":"Invalid handler specified"} 

![grafik](https://github.com/tschamm/boschshc-hass/assets/63980336/43f2fae2-8327-4d2e-99af-517124ba187f)

HA Version: 2023.12.4
SHC Version: 10.20.3505-29944 

Any ideas? Thanks a lot in advance!
Leon

**Comment by tschamm** [comment]
If you do not have a specific reason, then please try to go to HA 2024.03. and try again. 
I think you need to share some more details from the log.

**Comment by leonbittner** [comment]
This solved the issue, thanks a lot!
