### ISSUE TITLE
Connection failed

### ISSUE THREAD

**Issue by dz1984sg** [tschamm/boschshc-hass#179]
Can't connect to my control center, I can connect with my test instance ?

It does not show the control center in the recognition either 

is there perhaps something written somewhere in a file that it ignores the central ?

**Comment by dz1984sg** [comment]
Logger: root
Quelle: custom_components/bosch_shc/config_flow.py:72
Integration: bosch_shc ([Dokumentation](https://github.com/tschamm/boschshc-hass/blob/master/README.md), [Probleme](https://github.com/tschamm/boschshc-hass/issues))
Erstmals aufgetreten: 10:17:11 (1 Vorkommnisse)
Zuletzt protokolliert: 10:17:11

Failed to get public information from SHC controller: HTTPSConnectionPool(host='192.168.178.207', port=8446): Max retries exceeded with url: /smarthome/public/information (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4d771d90>: Failed to establish a new connection: [Errno 113] Host is unreachable'))

**Comment by tschamm** [comment]
Seems more like a local network issue on your side. Please check if the HA instance can reach the SHC.

**Comment by fuechti** [comment]
I have the same issue. Already two times. 

How have you solved the topic?

**Comment by tschamm** [comment]
no more reports here
