### ISSUE TITLE
bosch_shc.scenario_trigger event not working

### ISSUE THREAD

**Issue by JanZimmer** [tschamm/boschshc-hass#18]
Since my last update, "bosch_shc.scenario_trigger" doesn't work anymore. However, if I listen to bosch_shc.event, I stell get the "SCENARIO" subtype event.

**Comment by tschamm** [comment]
There has been a breaking change with the last commit. 

All `bosch_shc` events are consolidated as `bosch_shc.event` trigger events. With this change, it is possible to create automation triggers directly from the device list. Devices which provide events are:

`WRC2`: Universal Switch devices, for upper/lower button pressed short/long
`MD`: Motion Detector devices, if a motion event is detected
`SHC`: All scenarios registered in the official Bosch Smart Home app, if the scenario is triggered.
This will invalidate previous events. Sorry for any inconvenience.
c.f. https://community.home-assistant.io/t/bosch-smart-home/115864/175?u=tschamm

Sorry, I should have deprecated the old event triggers first.

**Comment by JanZimmer** [comment]
@tschamm thanks :) actually at this point, alle your changes improve stuff so much, that some simple changes on my side are more than bearable.
Thanks for your quick response!
