### ISSUE TITLE
bug - Entity None (<class 'custom_components.bosch_shc.climate.ClimateControl'>)

### ISSUE THREAD

**Issue by misa1515** [tschamm/boschshc-hass#193]
In Home Assistant (recent version) showed create bug report on integration issue.
Screenshot attached.
![2024-09-13_19-15-49](https://github.com/user-attachments/assets/7a08fe96-ca55-4dbb-974f-04e7febcc34c)

**Comment by tschamm** [comment]
Thank you for reporting.

**Comment by Matze89x** [comment]
Hello, this has already been posted.
https://github.com/tschamm/boschshc-hass/issues/161

I would like to add what HA has said about this:
https://developers.home-assistant.io/blog/2024/01/24/climate-climateentityfeatures-expanded/

It would be nice if the error could be fixed soon.

**Comment by tschamm** [comment]
Fixed in version 0.4.91
