### ISSUE TITLE
Setup of the Integration not working

### ISSUE THREAD

**Issue by effe232** [tschamm/boschshc-hass#195]
When I try to add the Device it says reauthorization successful but won't appear in my devices in Home Assistant. Another User also mentioned this issue in the Simon42 Community so it seems not to be a problem only for me.

**Comment by effe232** [comment]
<img width="384" alt="image" src="https://github.com/user-attachments/assets/423b4872-9923-4537-8fb6-a21b50b1fb21">

**Comment by tschamm** [comment]
so is that a problem or not?

**Comment by gramels** [comment]
seems to be the same I experienced in https://github.com/tschamm/boschshc-hass/issues/210 and the discussion here. https://community.simon42.com/t/bosch-shc-laesst-sich-nicht-integrieren/32259/9

Please let me know what I also can do and how to test for you.

**Comment by effe232** [comment]
> so is that a problem or not?

Yes, because it only states that the authentication was successsful, but no devices appear in Home Assistant.

**Comment by gramels** [comment]
Not sure if relevant, the integration needed to be manually configured, even though zeroconf seems to be running (I see messager from SHC on the network).
I do rund HA OS in a Proxmox Guest.

**Comment by gramels** [comment]
that fixed it (thanks to https://community.home-assistant.io/t/bosch-smart-home/115864/415 )

> - made sure to have a full backup
> - stopped HA ( core stop from console in proxmox)
> - removed the entry from “core.config_entries” inside the hidden “.storage” folder. If you browse the file the entry for SHC is easy to identify, either by the hostname, MAC or the parameters for the PEM-Files. The SMB AddIn might be helpful to alter the file while HA itself is offline
> - start HA from console

Seems the line was broken and introduced by the other bosch_shc installation. Likely a bug, as there is a name collision between the two bosch_shc versions.

@tschamm can you check how to remove the name collision or have the integration check for broken config lines?

**Comment by effe232** [comment]
Sounds quite conplicated as im running my has on my nas vm hypervisor. I have to take a look after christmas but it is very annoying that it isn‘t working for months.

**Comment by tschamm** [comment]
I'll look for an option how to re-authorize with new paths. If someone is aware of an option how to use path relative to the config directory.

**Comment by gramels** [comment]
Hi @effe232 

> Sounds quite conplicated as im running my has on my nas vm hypervisor.
You might use the terminal/ ssh plugin in HA to get to that file (while core is still running) and then restart core (at your own risk, no backup, mercy). The file pluglin seems not to show hidden directories. Or use the console in your hypervisor and then a command line text editor (like vi). Or use sed https://stackoverflow.com/questions/5410757/how-to-delete-from-a-text-file-all-lines-that-contain-a-specific-string to dele the line with _SHC .

> I have to take a look after christmas but it is very annoying that it isn‘t working for months.
Well, feel free to contribute. This is open source, with only 1 pro bono maintainer. I spent hours to find the root cause and happy now.

**Comment by effe232** [comment]
Yes, i know that. I meant this is annoying regarding home assistant that they didnt implemented a detection for cases like this.

**Comment by mosandlt** [comment]
This is the Core-vs-HACS `bosch_shc` **domain collision**: both the built-in integration and the HACS custom component use domain `bosch_shc`, and a stale Core config entry can block the HACS one from initialising. Fix: ensure only one is active — if you're HACS-only, remove the built-in entry; if a stale entry remains in `.storage/core.config_entries`, delete the `domain: bosch_shc` entry that points at the core install and restart. Leaving open as it's a structural overlap several users hit (see also #239).

**Comment by mosandlt** [comment]
Is this still happening on a current HA + **boschshc-hass 0.7.6**? This was the HACS-vs-Core domain collision (`bosch_shc`). If you still hit it, which HA version, and do you have both the Core and HACS integrations active?
