### ISSUE TITLE
deprecated - STATE_ALARM Info

### ISSUE THREAD

**Issue by Matze89x** [tschamm/boschshc-hass#200]
Hello, just for information without high prioritisation :-) 

STATE_ALARM_ARMED_HOME was used from bosch_shc, this is a deprecated constant which will be removed in HA Core 2025.11. Use AlarmControlPanelState.ARMED_HOME instead, please report it to the author of the 'bosch_shc' custom integration
STATE_ALARM_ARMING was used from bosch_shc, this is a deprecated constant which will be removed in HA Core 2025.11. Use AlarmControlPanelState.ARMING instead, please report it to the author of the 'bosch_shc' custom integration
STATE_ALARM_DISARMED was used from bosch_shc, this is a deprecated constant which will be removed in HA Core 2025.11. Use AlarmControlPanelState.DISARMED instead, please report it to the author of the 'bosch_shc' custom integration
STATE_ALARM_PENDING was used from bosch_shc, this is a deprecated constant which will be removed in HA Core 2025.11. Use AlarmControlPanelState.PENDING instead, please report it to the author of the 'bosch_shc' custom integration
STATE_ALARM_TRIGGERED was used from bosch_shc, this is a deprecated constant which will be removed in HA Core 2025.11. Use AlarmControlPanelState.TRIGGERED instead, please report it to the author of the 'bosch_shc' custom integration

Entity None (<class 'custom_components.bosch_shc.alarm_control_panel.IntrusionSystemAlarmControlPanel'>) is setting state directly which will stop working in HA Core 2025.11. Entities should implement the 'alarm_state' property and return its state using the AlarmControlPanelState enum, please report it to the custom integration author.

Thank you

**Comment by hafnerra** [comment]
same here

**Comment by tschamm** [comment]
Fixed in c188219a8e84fde59614aab33299294fc64f8aa6
