### ISSUE TITLE
Upgrade not Possible

### ISSUE THREAD

**Issue by Dani22m** [tschamm/boschshc-hass#207]
Hi Together!
I try to update the Bosch_SHC-Plugin.

I copy all Files from git /master/custom_components into /config/custom_components/bosch_shc and replace all existing files.

After a restart of Homeassistent (core: 2024.2.1 , Frontend: 20240207.1) I got the Error-Message:

```Logger: homeassistant.setup
Source: setup.py:404
First occurred: 16:07:28 (1 occurrences)
Last logged: 16:07:28

Unable to prepare setup for platform 'bosch_shc.alarm_control_panel': Platform not found (cannot import name 'AlarmControlPanelState' from 'homeassistant.components.alarm_control_panel.const' (/usr/src/homeassistant/homeassistant/components/alarm_control_panel/const.py)).```

How Ican solve that?

**Comment by armin-gh** [comment]
Any specific reason to run this old version of HA? You have seen that the newest version of this integration ( 0.4.92) requires HA 2024.11.0 or newer?
