### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by philjak** [tschamm/boschshc-hass#21]
Hello everyone,

just bought a Bosch Smart Home Kit because of the possibility to integrate it into HA. Unfortunately, I have issues connecting my HA with my SHC. Even the IP is correct (I already create a key-pair and added the client), I got this message:

![image](https://user-images.githubusercontent.com/5772650/107816137-9d711580-6d74-11eb-837d-bf40422df5bf.png)

My HA is running in a docker environment.

Does anyone have an idea, why this happens?

Thanks!
Philip

// Edit:
My machine has two different IPs in two different networks. Could this cause the problem? But I can see other hardware like Blink, Tado, Hue without any problems.

// Debug info
## System Health

version | 2021.1.5
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 4.15.0-112-generic
arch | x86_64
timezone | Europe/Berlin

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4682
Installed Version | 1.11.2
Stage | running
Available Repositories | 746
Installed Repositories | 1

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
mode | storage
views | 1
resources | 0

</details>

**Comment by tschamm** [comment]
@philjak Please check if your docker installation works properly with mDNS. For the configuration option of the HA discovery, see [here](https://www.home-assistant.io/integrations/discovery/#mdns-and-upnp).

**Comment by philjak** [comment]
Hey @tschamm,

Thanks for your quick reply. And thanks for the hint! You're probably right. But I think there is no way for me to get mDNS running. The server running HA is connecting to my home network (Fritz!Box) via VPN. 

Is mDNS mandatory for the functionality of Bosch and HA? I didn't have any issues with other integrations so far. 

Best regards,
Philip

**Comment by tschamm** [comment]
@philjak I changed the behavior to create a unique id to your suggestion with commit 71bc659. Can you check if this works for you? You will observe a warning in your HA logs instead.

**Comment by philjak** [comment]
Dear @tschamm,

first of all: Thank you so much for spending time in helping me with that issue. I really appreciate it!

Unfortunately, it seems not work. I get an `Unexpected error` now. I have to say, I reinstalled the repository with HACS. But I guess this is automatically using the latest master commit? Or do you recommand cloning and copy & pasting the folder to HA?

![image](https://user-images.githubusercontent.com/5772650/107862027-24dc8880-6e4a-11eb-93ed-ed7c095a95e4.png)

```
Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/bosch_shc/config_flow.py", line 61, in async_step_user
    self.info = info = await self._get_info(host)
  File "/config/custom_components/bosch_shc/config_flow.py", line 168, in _get_info
    information = await self.hass.async_add_executor_job(session.mdns_info)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/boschshcpy/session.py", line 240, in mdns_info
    return SHCInformation(api=self._api, zeroconf=self._zeroconf)
  File "/usr/local/lib/python3.8/site-packages/boschshcpy/information.py", line 64, in __init__
    raise SHCAuthenticationError
boschshcpy.exceptions.SHCAuthenticationError
```

**Comment by tschamm** [comment]
I'm looking into the source of the error currently, as I just found the same error in my setup.

**Comment by tschamm** [comment]
@philjak Please give it another try. Default headers were not allowed for `publicinformation` the rest call.

**Comment by philjak** [comment]
@tschamm You are my hero.

![image](https://user-images.githubusercontent.com/5772650/107863188-6c671280-6e52-11eb-9956-7c2541514e50.png)

Thank you very much - for helping me with this issue as well as for keeping up this project!

**Comment by tschamm** [comment]
You're welcome.
