### ISSUE TITLE
Battery level always 100%

### ISSUE THREAD

**Issue by jo-me** [tschamm/boschshc-hass#22]
Hi,
all of my thermostats show 100% battery level, even the ones I have used for months.

Is this a bug or (mis)reported by the gateway?

Thanks!

**Comment by tschamm** [comment]
Battery state is only reported as `low` or `critical low`, everything else is equal to `full` via API. So it‘s fine your devices report 100% so far. 

Low is equal to 20%, critical low 0%, if you want to write automations based on these values.
