### ISSUE TITLE
Sensor from Thermostate not found

### ISSUE THREAD

**Issue by bitdevil007** [tschamm/boschshc-hass#25]
Hi,
the temperatur-sensor from the Thermostate is not found in the Integration.
In the climate.room sensor will ist works but i want the temperatur-sensor separately.
How can i catch the Sensor?

Can you help me?

**Comment by tschamm** [comment]
The temperature value is represented as a sensor entity, e.g. sensor.thermostat_kitchen.

**Comment by bitdevil007** [comment]
Now i have found it, sorry.
