### ISSUE TITLE
Door Sensor in Automation

### ISSUE THREAD

**Issue by christianreiss** [tschamm/boschshc-hass#26]
First off,

thank you for some great work. I was following your merge request on HASS which is nearing its first birthday. Congratulations on a 1-year old request and your tenacity :)

The entire thing works like a charm and my Bosch stuff (underfloor heating controls, shutter controls, smoke detectors, twinguards etc) work great. The only thing thats a little off is the door sensor. It does detect them all, and instantly shows in lovelace that a door is opened or closed, but I cant act on them.

Basic thing: I want to turn off/on a light if a door is opened. I tried as trigger....

Device: Trigger is unkown trigger,
State: tried On, Off, Open, Opened, Closed, true, false, 0, 1... nothing triggers.

I also tried Developer Tools -> States -> Door Sensor: State is always off and the yaml only shows

friendly_name: Büro Tür
device_class: window

What am I missing here?

**Comment by tschamm** [comment]
@christianreiss thank you for reporting this bug. The access to the session object for device triggers did not work anymore after the last update.
Now you should be able to select a device (e.g. Büro Tür) and choose between `opened` and `closed`. 

However, you can also select an entity and watch if its state is `on` (Opened) or `off` (Closed) like you suggested using Developer Tools.

**Comment by christianreiss** [comment]
I can confirm it works -- thank you very much!
