### ISSUE TITLE
Universal Switch not working after HA 2021.7 update

### ISSUE THREAD

**Issue by therealhalifax** [tschamm/boschshc-hass#29]
After I update my Home Assistant core to 2021.7 today the Universal Switch does not work anymore. I mean its shown as entity but in the Automation only the battery level could be selected as trigger, but not anymore the button press events.

**Comment by therealhalifax** [comment]
@tschamm thanks for the fast bug fix. with your update it works now :-)

**Comment by tschamm** [comment]
Fixed with be86f17
