### ISSUE TITLE
Enable/Disable Alarmpanel with presence detection

### ISSUE THREAD

**Issue by h4sk33r** [tschamm/boschshc-hass#37]
Hi,

thank you very much for this nice integration. Can you please help me with a couple of questions regarding the integration, as I am new to HA and python/YAML:
1. how to enable/disable the alarm_panel with an automation?
2. is there a way to add a Smoke detector to the HA alarm panel as a siren?

Basically i want to ditch the Bosch APP for everything except the initial device setup.

Thank you very much.

**Comment by tschamm** [comment]
Hi @h4sk33r,
did you proceed with enabling/disabling the alarm_panel? Currently, there is no documented way to use the smoke detectors as a siren.
Best, Thomas

**Comment by h4sk33r** [comment]
Hi,
Thank you very much for responding back. In the end I did find the way to enable the alarm panel with an automation.
For everyone also needing help:

`action:
  - service: alarm_control_panel.alarm_arm_home // alarm_control_panel.alarm_disarm
    target:
      entity_id: alarm_control_panel.intrusion_detection_system`
