### ISSUE TITLE
Shutter contact position reversed

### ISSUE THREAD

**Issue by moritzbeck01** [tschamm/boschshc-hass#38]
First of all; thanks for the great integration! If you need any testers I'm happy to help with whatever I can.

I noticed that when using the shutter contacts, the reported position is inverted. E.g. "0" is closed and "100" is open, which I find counterintuitive. The open and close buttons do work correctly, though.
I found no easy way to fix this for all shutters at once, but it can certainly be done with a script for each device. It just needs something like "inverted = 100 - position".
Maybe inspiration from the Z-Wave integration can be taken (https://www.home-assistant.io/integrations/zwave). It has the options "invert_openclose_buttons" and "invert_percent".
Even if this breaks some existing installations when updating, I think that this behavior should be the default, not the other way around.
I did notice that using the Google Assistant on the controller directly shows the same behavior. I am also not quite sure if this or the boschshcpy repository is the right place to post this.

Thanks in advance. I might try to write my own fix for now and will post it here if I succeed.

**Comment by moritzbeck01** [comment]
See https://github.com/tschamm/boschshc-hass/pull/39 for the pull request.

**Comment by tschamm** [comment]
Thanks @moritzbeck01 for your suggestion. For the boschshcpy library, the library just reports the states and does not do any interpretation of the values. Actually I'm not getting you point, so maybe you can help me to fully understand the issue:
Within the Bosch App, a fully closed cover has position 100%, the Bosch API reports the level with 0., this is why a closed cover is processed in boschshcpy with level 0, a fully open cover with level 100. The [home assistant cover template doc](https://www.home-assistant.io/integrations/cover.template/#position_template) defines legal values are numbers between 0 (closed) and 100 (open). I can see your point with adding an option to invert percentage, but I would not change it as a default.
You mentioned Google Assistant also has problems setting the correct position. Is this just for intermediate positions (e.g. 30 percent) or also for the open and close behavior?

**Comment by moritzbeck01** [comment]
I did not know about the requirements by the Home Assistant Docs. Though it seems counterintuitive to me, especially when it's reversed in the Bosch App, I guess you have to and it's better for compatibility to comply to those guidelines.

The open and closed states are being reported correctly, they do not need to be reversed like in my pull request. The underlying issue was on my side.

Google Assistant has the same weird interpretation as Home Assistant. When you tell it to set the position to 30, it closed the shutter by 70%. Telling it to open and close is, just like in Home Assistant, fine.
I guess fully opening and closing are separate functions that are integrated differently and do not just set the position to 0 or 100. Looking at the code this assumption seems to be correct.

If would be very helpful to implement an inverse option, but this won't be able fix all the issues in Home Assistant. Even though fully opening and closing do apparently not utilize the set_position function, you cannot use the buttons to do this when the shutter is at position 0 or 100 respectively.
This seems to be because Home Assistant thinks that 0 is fully closed (which it is not, after inversing it is fully open now), so you cannot use the close button because it is greyed out. There has to be a check somewhere that basically says: If the position is already at 0 (closed from Home Assistant's point of view), you cannot use the close function (because it thinks that it is closed already, which it is not). The same goes for opening when the position is at 100.

After reading the docs it makes more sense to me to advocate to an inverse option on Home Assistant's side. Then it would probably be possible to also fix the unintentional behavior mentioned above. Do you have any idea where that check could be in Home Assistant's code base?

**Comment by moritzbeck01** [comment]
I think it happens [here](https://github.com/home-assistant/frontend/blob/master/src/components/ha-cover-controls.ts) in the first two functions.
I cannot find that file within my Home Assistant installation. Any idea how I can modify it on my end easily?
