### ISSUE TITLE
Exception discovery_info.get('name') since 2021.12

### ISSUE THREAD

**Issue by Gloomyeye** [tschamm/boschshc-hass#40]
Hello,

I get the following error message with the current 2021.12 beta of home assistant:

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:103
First occurred: 07:23:36 (1 occurrences)
Last logged: 07:23:36

Detected integration that accessed discovery_info.get('name') instead of discovery_info.name; this will fail in version 2022.6. Please report issue to the custom component author for bosch_shc using this method at custom_components/bosch_shc/config_flow.py, line 186: if not discovery_info.get("name", "").startswith("Bosch SHC"):

I know version 2022.6 is a long time away, so it's not a real problem yet.

**Comment by tschamm** [comment]
Thank you for having a look also on compatibility with beta versions of home assistant. The necessary changes have been introduced already within release 0.4.19 with commit fab0fc9befd148766a6199f3b1bf2e80bc9e3c56.
