### ISSUE TITLE
Trouble installing

### ISSUE THREAD

**Issue by Dherlou** [tschamm/boschshc-hass#44]
Hey guys,

I want to control my Bosch light switch controls from inside HA.

I have tried installing the `Bosch SHC`-Integration in `Configuration->Integrations->Add Integration->Bosch SHC`. However, I only get two sensor entities (`sensor.*_energy` and `sensor.*_power`) created in Home Assistant over this integration and hence cannot control the switches over them.

Later on, I found your integration, which is a different one, am I correct about this? The readme states that it supports light control switches, so I guess that is my use case. So I tried installing it, but didn't come far. I tried both installing the `Bosch Smart Home Controller (SHC) integration` via HACS (which is this integration, isn't it?) and via manual file deployment inside `custom_components`. However, after restarting HA, it doesn't automatically show up under `Configuration->Integrations`. When I press `Add Integration`, it shows a `Bosch SHC`, but this is again the official one from my first try, isn't it? If I click on it, it hangs a moment with the message `Please wait while the integration is being installed` andafter a few seconds it tells me: `Error - Config flow could not be loaded`.

What am I doing wrong?
Thanks for the clarifications and tips in advance!

Sincerely, Lucas

**Comment by klemmchr** [comment]
>  have tried installing the Bosch SHC-Integration in Configuration->Integrations->Add Integration->Bosch SHC. However, I only get two sensor entities (sensor.*_energy and sensor.*_power) created in Home Assistant over this integration and hence cannot control the switches over them.

> Later on, I found your integration, which is a different one, am I correct about this?

The official integration is this integration but integrated into the official repository of hass. This is still WIP and being worked on. The official integration gives you no benefit over the custom component (besides easier installation).

> When I press Add Integration, it shows a Bosch SHC, but this is again the official one from my first try, isn't it? If I click on it, it hangs a moment with the message Please wait while the integration is being installed and after a few seconds it tells me: Error - Config flow could not be loaded.

If you added the custom component properly it will show up in your integrations without the need to manually add it. If you add it manually, this will take the official integration and not the custom component. They cannot be installed side by side. If the integration does not show up properly in your integrations panel you did something wrong.

Make sure that the custom component is installed in a subdirectory of `custom_components` (e.g. `/config/custom_components/bosch_shc`). Pasting it into the root folder of `custom_components` does not work. For me, the integration is found after restarting hass.

**Comment by klemmchr** [comment]
I managed to install it. Adding the custom integration plus restarting plus clearing cache does the trick. If you see an auto discovered integration there should be a little icon indicating it's a custom component. If this doesn't show up just add the integration manually (like with every other integration). It will use the custom component instead of the official integration.

**Comment by Dherlou** [comment]
Alright, thanks for the clarification, @klemmchr .
I will try your tip regarding the installation after work today. :)

**Comment by Dherlou** [comment]
Hey @klemmchr ,

I was able to get this custom component working now. All of my devices and entities are detected and controllable perfectly fine now. I also updated HA to 22.02, maybe it was a problem with my old 21.9(?) version of HA that I had been running before. Anyways, it gets the job done perfectly now. Thanks for your help. :)
