### ISSUE TITLE
Feature Request: Show valvetappet on climate card

### ISSUE THREAD

**Issue by Crumar** [tschamm/boschshc-hass#45]
Hi,

love the custom component. After upgrading from the builtin, I can do a lot more than before. However, I'd like to see the valvetappet in the climate card. 
I think this might be difficult because there can be multiple radiator thermostats in one climate service, and I am not yet experienced enough with HA, but would like to chip in as well.

Can you provide some guidance where I need to start?
I think the climate.py needs to be extended to return a list of valve (names and tappet), and then a custom card needs to be added which is derived from the builtin card that. Is that the correct approach?

**Comment by nikf86** [comment]
I am trying to achieve the exact same thing but additionally exposing them to homekit. Currently i am trying to expose the valvetappet entities to homekit alone but with no success. If this value could be shown directly in the climate sensor card i think it would be then directly exposed to homekit also.

**Comment by saxn-paule** [comment]
@Crumar what about rooms with more than one TRV? Which value should be shown?

All thermostats beeing in one room are grouped and synched. In my case I a have a room thermostat and two TRVs.

In sum, there are three thermostats available in HA, but which one should be shown in the climate card? Usually the room climate that doesn't provide a valvetappet attribute.

**Comment by Crumar** [comment]
@saxn-paule 
I have the same in one room, two radiators and one room thermostat. 
If possible all of them, or other solution could be min/max/avg. Maybe even depending on how many there are? 
Havent done any HA development yet, so I dont know if thats feasible, but without any hints I havent even tried to look in depth yet.

**Comment by tschamm** [comment]
@saxn-paule is right, a climate card shows the temperature of the room. 
You can create a custom card and then add all valve tappet sensors of a single room to show up there.
