### ISSUE TITLE
Lux from Motion Detector

### ISSUE THREAD

**Issue by TomF79** [tschamm/boschshc-hass#47]
Hi, thanks for your great Integration.
Is it possible to integrate a Lux Sensor from the Motion Detector?

BR Tom

**Comment by tschamm** [comment]
Fixed in https://github.com/tschamm/boschshc-hass/commit/5c073dbe7bbe7fd473795fb6b9942f3f0a877c3a
After updating to 0.4.48, you'll have a new entity with reports the illuminance level of the motion detector. Just be aware the update frequency is rather low.
