### ISSUE TITLE
[Question] Trigger alarm of all smoke detectors simultaniously

### ISSUE THREAD

**Issue by saxn-paule** [tschamm/boschshc-hass#48]
Is it possible to trigger the siren of all smoke detectors simultaniously based on an HA automation? If yes, how?

**Comment by Schnabulation** [comment]
I'd like to know this as well: is it possible to manually trigger the siren of the smoke detectors via Home Assistant?

**Comment by saxn-paule** [comment]
> I'd like to know this as well: is it possible to manually trigger the siren of the smoke detectors via Home Assistant?

As a Workaround, trigger the test signal every 10 seconds in a loop.

**Comment by Schnabulation** [comment]
Thank you for that suggestion!

Do you know what the other service "Bosch SHC: smokedetector_alarmstate" does? I didn't find any documentation in this regard.

**Comment by saxn-paule** [comment]
I think it will show if the alarm is triggered. During test alarm the state doesn't change.

Try it with some cigarette smoke ;)

**Comment by saxn-paule** [comment]
> Thank you for that suggestion!
> 
> Do you know what the other service "Bosch SHC: smokedetector_alarmstate" does? I didn't find any documentation in this regard.

I think it will show if the alarm is triggered. During test alarm the state doesn't change.

Try it with some cigarette smoke ;)
