### ISSUE TITLE
Failed to get public information from SHC Controller

### ISSUE THREAD

**Issue by hafnerra** [tschamm/boschshc-hass#49]
Hello,

i get after the upgrade to version 04.25 following error in the Log:

Logger: root
Source: /srv/homeassistant/lib/python3.9/site-packages/boschshcpy/api.py:142
First occurred: 16:57:11 (3 occurrences)
Last logged: 16:58:33
Failed to get public information from SHC controller: Could not find a suitable TLS CA certificate bundle, invalid path: /srv/homeassistant/lib/python3.9/site-packages/boschshcpy/tls_ca_chain.pem

Is there a Bug or have someone a solution for this problem.

I run the newest Home Assistant version. Its a venv installation.

Thanks for help!

**Comment by tschamm** [comment]
Hi,
can you see which version of boschshcpy has been installed? Actually the pem was not removed, why it is missing is unclear. 
I guess you already tried a restart?

**Comment by hafnerra** [comment]
I have Bosch SHC updated with HACS to 0.4.25. Then i restarted HA. I tried to delete and reinstall too, but always the same issue.
Where can i see the boschshcpy version?

**Comment by hafnerra** [comment]
i have overwritten the files from this git repo 
https://github.com/tschamm/boschshcpy
in following path
/srv/homeassistant/lib/python3.9/site-packages/boschshcpy

Now it work as before. I dont know why this is happen.

But thanks for help!

**Comment by tschamm** [comment]
Hi @hafnerra 
still wondering whats the reason for this behavior. Maybe pip did not install the boschshcpy 0.2.29 version correctly. I just verified on my machine, the pem file is installed correctly after a `pip install boschshcpy==0.2.29`.
I'll reopen the ticket if I find out the reason behind...
