### ISSUE TITLE
Lot of failures und Log

### ISSUE THREAD

**Issue by TomF79** [tschamm/boschshc-hass#50]
Since Last Update there are a lot of failures in the Log.

<img width="820" alt="PNG-Bild3" src="https://user-images.githubusercontent.com/93859783/157622398-a2d10904-c780-44b8-b2d8-516dd8fa3273.png">

**Comment by tschamm** [comment]
Thanks for reporting. Are these errors reported after each restart?

**Comment by TomF79** [comment]
Now I deleted all failures in Log and will look which shows up again.

**Comment by tschamm** [comment]
Hi @TomF79, there was an update of the SHC rolled out these days. Maybe these errors result from the auto-update of the SHC.

**Comment by TomF79** [comment]
Thanks for the Info. Till now there are no new failures since this morning. Maybe they were after a restart or from the auto update.

**Comment by tschamm** [comment]
I'll close the issue then. Please reopen if problems come up again.
