### ISSUE TITLE
Feature support humidity and other sensor data in statistics card

### ISSUE THREAD

**Issue by kaystrobach** [tschamm/boschshc-hass#53]
Hi,

in lovelace you can create a multi value statistucs graph. Sadly the humidity of the twin guard and the thermostats can not be added.

please make this possible.

thank goodness you.

**Comment by tschamm** [comment]
Hi, I added statistic features for sensor platform in 0.4.27, I changed the status from pre-release to release today.
![Bildschirmfoto 2022-03-20 um 20 06 11](https://user-images.githubusercontent.com/31720/159178544-d9ce733d-82b4-46a8-8d6e-16fa3614bb8d.png)

**Comment by kaystrobach** [comment]
Awesome, just installed it. Graph card was created, now waiting for data. Thank you.
