### ISSUE TITLE
Setup failed for custom integration bosch_shc: Requirements for bosch_shc not found: ['boschshcpy==0.2.31'].

### ISSUE THREAD

**Issue by u20p17** [tschamm/boschshc-hass#55]
Hi,
since the last update (0.4.28) I get the following error:

> Unable to install package boschshcpy==0.2.31: ERROR: Could not find a version that satisfies the requirement boschshcpy==0.2.31 (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5.dev0, 0.1.5.dev1, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.1.10.dev0, 0.1.10, 0.1.11, 0.1.12.dev0, 0.1.12, 0.1.13, 0.1.14, 0.1.15.dev0, 0.1.15.dev1, 0.1.15.dev2, 0.1.15.dev3, 0.1.15.dev4, 0.1.15, 0.1.16, 0.1.17.dev0, 0.1.17, 0.1.18.dev0, 0.1.18.dev1, 0.1.18.dev2, 0.1.18.dev3, 0.1.18.dev4, 0.1.18.dev5, 0.1.19, 0.1.20, 0.1.21, 0.1.22, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.2.7.dev0, 0.2.7.dev1, 0.2.7, 0.2.8.dev0, 0.2.8.dev1, 0.2.8.dev2, 0.2.8.dev3, 0.2.8.dev4, 0.2.8.dev5, 0.2.9, 0.2.10, 0.2.11, 0.2.12, 0.2.13, 0.2.14, 0.2.15, 0.2.16.dev0, 0.2.16.dev1, 0.2.16, 0.2.17, 0.2.18, 0.2.19, 0.2.20, 0.2.21, 0.2.22, 0.2.23, 0.2.24, 0.2.25, 0.2.26, 0.2.27, 0.2.28, 0.2.29.dev0, 0.2.29.dev1, 0.2.29, 0.2.30) ERROR: No matching distribution found for boschshcpy==0.2.31 WARNING: You are using pip version 22.0.3; however, version 22.0.4 is available. You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.

HA OS and core version is the latest (core-2022.4.4, Home Assistant OS 7.6)

How can I fix this?

BR

**Comment by hafnerra** [comment]
Same problem here

**Comment by tschamm** [comment]
Sorry, missed uploading the package, issue should be fixed now.

**Comment by u20p17** [comment]
thanks! now I have no issues again (Y)
