### ISSUE TITLE
HomeCom / Heating Integration

### ISSUE THREAD

**Issue by Schopenhauer178** [tschamm/boschshc-hass#56]
Hi,

I'm using the Integration for a Long time now and like it very much. Heave you ever thought about integrating the gas heatings that can already be connected via Bosch HomeCom to the Bosch Smart Home? This would lead to a bunch of new functions like automations to turn on / off the water heating when home or not home for instance. Also the statistics for the solar water buffer temperatures could be stored.

Here is the link to the HomeCom integration:

https://www.bosch-homecom.com/de/de/boschhomecomeasy/ueberblick/ 

Best regards,
Sven

**Comment by tschamm** [comment]
Hi Sven,
via Bosch Smart Home, you can receive some parts of the HomeCon system. Support for HeatingCircuits of my own heatpump is already implemented in the 3rd party library. From my experience, a full featured Heating Integration can be achieved best by direct access to the EMS bus, e.g. [EMS-ESP devices](https://bbqkees-electronics.nl).

However I can add additional features, if you can provide me with respective log entries (json result of https://{{host}}:8444/smarthome/devices and https://{{host}}:8444/smarthome/services calls).
Best, Thomas

**Comment by Schopenhauer178** [comment]
Hi Thomas,

thanks for your reply, it gave me the right hint. I'm using the Bosch MBLani Module which is already connected to the EMS Port (probably kind of the same device like in your link). The MBlani module connects my Bosch smart home room thermostats to the central heating in order to change the central heating temperature set point automatically.

I used this integration on GitHub https://github.com/bosch-thermostat/home-assistant-bosch-custom-component together with this manual https://smarterkram.de/2126/

It works fine reading the sensors so far. The only thing I am missing is the possibility to change and activate the holiday mode, but I will try to find out if I can configure it manually via node red. It's working for the heating circuit already but I have to figure out if it's also working for the hot water configuration.

I think it's no needed then to integrate it in your integration.

Thanks again for your help,

Sven
