### ISSUE TITLE
Deprecated warning async_get_registry

### ISSUE THREAD

**Issue by Gloomyeye** [tschamm/boschshc-hass#57]
Hello,

the following warning message occurs at startup of home assistant (core-2022.6.7):

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:103
First occurred: 08:18:50 (1 occurrences)
Last logged: 08:18:50

Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom component author for bosch_shc using this method at custom_components/bosch_shc/device_trigger.py, line 47: dev_registry = await dr.async_get_registry(hass)

**Comment by tschamm** [comment]
Thank you for reporting. I fixed this with commit [9a72009](https://github.com/tschamm/boschshc-hass/commit/9a72009921851b32e48e525fbaed189ed4f511f2)
