### ISSUE TITLE
Switches not recognized in latest HA

### ISSUE THREAD

**Issue by dolodobendan** [tschamm/boschshc-hass#58]
Window contacts, power plugs, and the universal switch stopped working after upgrading to 2022.7.3. I think it worked fine with 2022.7.0 but I'm not sure. Reverting to 2022.6.7 made these devices available again.

BOSCH SHC is installed via HACS.

Thank you for your work!

**Comment by tschamm** [comment]
Actually I cannot confirm this. I am running 2022.7.3, not having any problems, neither with switch nor plugs. 
Maybe restart your SHC helps?

**Comment by dolodobendan** [comment]
Interesting. I restarted both SHC and HA to no avail. Since then there was an update for SHC, maybe it fixes things.
