### ISSUE TITLE
Add event on scenario triggering

### ISSUE THREAD

**Issue by JanZimmer** [tschamm/boschshc-hass#6]
According to BOSCH, there is a message sent via the longpoller whenever a scenario is triggered. It would be awesome, if this message could be translated into an event in HA. Thereby, e.g., the Twist Remote will be enabled to trigger scenarios in HA.

For reference, see https://github.com/BoschSmartHome/bosch-shc-api-docs/issues/38#issuecomment-709936391.

**Comment by tschamm** [comment]
I'll checked for this. What was already possible is to trigger a scenario from within HA, by using the service "boschshc.trigger_scenario".
With boschshcpy==0.1.9 I added the functionality for the other way around. It should now be possible to watch for the event "bosch_shc_scenario_triggered". The event will contain the name, id and lastTimeTriggered provided from SHC.

**Comment by JanZimmer** [comment]
Correction: event can be found under "bosch_shc.scenario_trigger"
