### ISSUE TITLE
Single thermostat as entity (next to room climate)

### ISSUE THREAD

**Issue by erd82** [tschamm/boschshc-hass#60]
I have multiple Bosch thermostats II in my apartment. If several thermostats are part of a room ...
![image](https://user-images.githubusercontent.com/63564291/188891487-39b4aeb6-a8e8-4f2e-b332-58f79cdbc2f8.png)

... in the mobile app > Favorites, these thermostats are combined in a room view (here a simple example). Finally only the average room temperature is displayed, not the single thermostat temperature.
![image](https://user-images.githubusercontent.com/63564291/188891722-caaace7e-371e-4ee3-9981-ad97aee7bdb6.png)

Is it possible to display the details for the single thermostat in Home Assistant?

I would also expect sensor data like the valve position.
![image](https://user-images.githubusercontent.com/63564291/188892758-458ff1da-c942-4ade-a9e7-cf0d981fa162.png)

Is there a way to show and use this in Home Assistant? Or is it the implementation planned for this integration?

Thanks & kind regards

**Comment by erd82** [comment]
Or could it be that the [Bosch Smart Home Radiator Thermostat II](https://www.amazon.de/Bosch-Smart-Home-Heizk%C3%B6rperthermostat-App-Funktion/dp/B0B6BWTMHW/ref=sr_1_30?adgrpid=71101403476&gclid=Cj0KCQjwguGYBhDRARIsAHgRm4_qIkxHPEDmCn8UAo-OkMYFrkXQ6Tv8iDYaZmnSKwX00BvHhR76c8caApaTEALw_wcB&hvadid=596070578061&hvdev=c&hvlocphy=9043142&hvnetw=g&hvqmt=b&hvrand=5589694648199988213&hvtargid=kwd-602116329&hydadcr=21830_2266874&keywords=heizk%C3%B6rperthermostat&qid=1662573903&sr=8-30) is not yet supported (see [HA Community discussion](https://community.home-assistant.io/t/bosch-shc-add-temperature-control/356123/5)) by this integration?

**Comment by erd82** [comment]
In the [HA Community discussion](https://community.home-assistant.io/t/bosch-shc-add-temperature-control/356123/5) we figured out that the [Bosch Smart Home Radiator Thermostat II](https://www.amazon.de/Bosch-Smart-Home-Heizk%C3%B6rperthermostat-App-Funktion/dp/B0B6BWTMHW/ref=sr_1_30?adgrpid=71101403476&gclid=Cj0KCQjwguGYBhDRARIsAHgRm4_qIkxHPEDmCn8UAo-OkMYFrkXQ6Tv8iDYaZmnSKwX00BvHhR76c8caApaTEALw_wcB&hvadid=596070578061&hvdev=c&hvlocphy=9043142&hvnetw=g&hvqmt=b&hvrand=5589694648199988213&hvtargid=kwd-602116329&hydadcr=21830_2266874&keywords=heizk%C3%B6rperthermostat&qid=1662573903&sr=8-30) is not yet known as thermostat by the “boschshcpy”-Library. In the logs it is shown as as device model “TRV_GEN2”.

**Comment by tschamm** [comment]
I added this functionality with boschshcpy==0.2.34, which is included in version 0.4.30. Fixed by [9a72009](https://github.com/tschamm/boschshc-hass/commit/9a72009921851b32e48e525fbaed189ed4f511f2)
