### ISSUE TITLE
One SHC and two HA instances?

### ISSUE THREAD

**Issue by dolodobendan** [tschamm/boschshc-hass#64]
Hi, I have two HA instances: One for daily use (HA), and one for testing purposes (TEST). It's only active on HA right now because as soon as I enable it on TEST, it stops working on HA (and vice versa). Is it possible to somehow connect both instances to one SHC? It would make testing things a lot easier.

**Comment by armin-gh** [comment]
Same scenario works without problems here.
And I doubt the SHC Controller knows the difference between a HA instance connected and any other client like a mobile phone, all are just clients allowed to connect and send/receive data using the REST-Interface.

Anything your two HA instances have in common, like IP-Address or MAC?

Armin

**Comment by dolodobendan** [comment]
> Same scenario works without problems here. And I doubt the SHC Controller knows the difference between a HA instance connected and any other client like a mobile phone, all are just clients allowed to connect and send/receive data using the REST-Interface.

Thank you, Armin, for your response. That was my assumption, too, but it never worked. I guess I'll just try it again.

> Anything your two HA instances have in common, like IP-Address or MAC?

Not sure what this could be. One instance is running on a raspberry pi, and the other on an ubuntu server.

**Comment by armin-gh** [comment]
Hi
the issue with the IP/MAC is something I have seen with cloned virtual machines, but this is obviously not the case here.

You are using the integration from HACS or installed it manually as custom integration? The integration included with HA has, as far as I know, still limited features

When I installed my initial system ( the one I'm using as "production" now), the integration could not directly register with the SHC, instead there were manual steps using the REST-Interface and Postman and downloading the certificate for the client. 

Sounds to me like it is overwriting the registration on the controller when you register the 2nd device? Perhaps related to the feature request (#66 ) just posted here?

Armin

**Comment by dolodobendan** [comment]
> Hi the issue with the IP/MAC is something I have seen with cloned virtual machines, but this is obviously not the case here.



> You are using the integration from HACS or installed it manually as custom integration? The integration included with HA has, as far as I know, still limited features

At the moment only the raspberry instance ("production") has the HACS version installed.

> When I installed my initial system ( the one I'm using as "production" now), the integration could not directly register with the SHC, instead there were manual steps using the REST-Interface and Postman and downloading the certificate for the client.
> 
> Sounds to me like it is overwriting the registration on the controller when you register the 2nd device? Perhaps related to the feature request (#66 ) just posted here?

I saw that, too. Maybe? I just remembered that I couldn't install the HACS version on my test system. I'll try again.

--

I could install it this time, but I have the same error as before:

![image](https://user-images.githubusercontent.com/37902856/200356826-f0ef04c7-8d2f-4b9f-9a48-fca8e7619287.png)

![image](https://user-images.githubusercontent.com/37902856/200356854-79abae80-9bbf-4439-8cc8-4f4ad21d72fa.png)

**Comment by armin-gh** [comment]
After registering your main system again, you can try the following ( until the feature request in #66 leads to an official solution):
Modify config_flow.py line 46 on your test system and change
`result = helper.register(host, "HomeAssistant")
`
to something like
`result = helper.register(host, "HomeAssistantTest")
`
This is executed only once to retrieve the certificate from the controller, after registration you can put back the official code

Armin

**Comment by dolodobendan** [comment]
Thank you, I'll give it a try as soon as I find that file on the test system.

One thing I should have mentioned before: On the test system, HA and HACS are installed via snap.

**Comment by armin-gh** [comment]
hmm...
can't help with snap, both my installation are running Home Assistant Core in a Python venv
but if you changed the code on the normal system, this only helps if you re-registered the normal system with the controller.
When using the SHC-App on a mobile device and going to (sorry, only have the german wording), "Mehr", "Mobilgeräte" you see a list of registered devices. One of them is named "oss_HomeAssistant_Binding", that's the device registered with the integration in HomeAssistant. The registration itself is not directly in the code for the integration, that's provided by "boschshcpy"-Python-Library. 
The "oss" and "Binding" part of the name is fixed, the middle part "HomeAssistant" is set in the part of the code mentioned above. If you changed the code AND registered your HA-Integration again, you would see a device with the new name in the list.
That's also what the feature request in the other issue is about, to get a different name for the Controller if you have multiple HA installations

Armin

**Comment by dolodobendan** [comment]
> hmm... can't help with snap

Snap can be annoying. I had some trouble with NextCloud. 

> if you changed the code on the normal system, this only helps if you re-registered the normal system with the controller.

Of course. Since I had I alternated between having to register the test system and the regular system, there was plenty of time to get the new name from the new code.

>When using the SHC-App on a mobile device and going to (sorry, only have the german wording), "Mehr", "Mobilgeräte" you see a list of registered devices.

Coincidentally, German is the system's language on my phone. 😉

> One of them is named "oss_HomeAssistant_Binding", that's the device registered with the integration in HomeAssistant. The registration itself is not directly in the code for the integration, that's provided by "boschshcpy"-Python-Library. The "oss" and "Binding" part of the name is fixed, the middle part "HomeAssistant" is set in the part of the code mentioned above. If you changed the code AND registered your HA-Integration again, you would see a device with the new name in the list. That's also what the feature request in the other issue is about, to get a different name for the Controller if you have multiple HA installations

Huh. I do NOT thee the expected "oss_HomeAssistantRPi_Binding" here.

![image](https://user-images.githubusercontent.com/37902856/200665539-aeeb0d93-2f62-41f2-aea9-37ea6a1dbb6a.png)

I'll try and reinstall the integration, see what happens.

**Comment by armin-gh** [comment]
hi
the location of the file is custom_components/bosch_shc, absolute path differs depending on type of installation, for my Python venv it is /home/homeassistant/.homeassistant/custom_components/bosch_shc

not sure if this also depends on the type of installation, in the integrations page my Bosch SHC is flagged as custom component in the upper right corner. Like all other integrations I downloaded via HACS or installed manually. I don't see that in your screenshots?
![image](https://user-images.githubusercontent.com/71582770/200880036-0efafa0f-47b6-4b8e-8359-432ba8e41608.png)

Armin

**Comment by dolodobendan** [comment]
Hi Armin,

both installations are HACS installations with this box thingy in the upper right corner:

![image](https://user-images.githubusercontent.com/37902856/200891100-d16521f1-303b-44f5-8427-60ea556b18e9.png)

It is safe to assume that I edited the right file as the change in the binding's name was adopted IF there was no existing binding.

**Comment by armin-gh** [comment]
seems more to be behind the registration process than I thought...

my main system is still using the initial way to register a device for the controller, you had to manually create the certificate and the key for the client and then register the device using "postman", as decribed here 
https://github.com/BoschSmartHome/bosch-shc-api-docs/tree/master/postman
to configure the integration you then had to provide locations for certificate and key
my test system was registered the "new" way, with the certificate and key being created by the integration.

That's perhaps really hacker style, but if you go through the process for a manually registered device, you may replace the certificate and key created by the integration with the certificate and key used for manual registration, of course using the filenames as expected by the integration.
Which files are used for certificate and key is stored in /config/.storage/core.config_entries

Armin

**Comment by dolodobendan** [comment]
> seems more to be behind the registration process than I thought...
> 
> my main system is still using the initial way to register a device for the controller, you had to manually create the certificate and the key for the client and then register the device using "postman", as decribed here https://github.com/BoschSmartHome/bosch-shc-api-docs/tree/master/postman to configure the integration you then had to provide locations for certificate and key my test system was registered the "new" way, with the certificate and key being created by the integration.
> 
> That's perhaps really hacker style, but if you go through the process for a manually registered device, you may replace the certificate and key created by the integration with the certificate and key used for manual registration, of course using the filenames as expected by the integration. Which files are used for certificate and key is stored in /config/.storage/core.config_entries
> 
> Armin

Thank you, I'll give the manual registration a try!

**Comment by tschamm** [comment]
Sorry for letting you wait. You are right, the last controller registered using Home Assistant wins. This is due to the fact, that the device name for the certificate in the SHC is hardcoded here:
https://github.com/tschamm/boschshc-hass/blob/67fc390f056b3ecee9243242acb9e329fa8535a6/custom_components/bosch_shc/config_flow.py#L46
When a new HA instance is registered, a certificate with the same name will be overwritten in the SHC.

I will extend the config flow dialog to provide a custom name.

**Comment by tschamm** [comment]
Fixed in 116118d04fcd22538b405232cb5b9fb329239036, shipped in version 0.4.42
