### ISSUE TITLE
compatibility issues - Bosch Door / window contact II !?

### ISSUE THREAD

**Issue by techsupportaifb** [tschamm/boschshc-hass#67]
Hi there, 

I managed to conect my Bosch Controller to Home Assistant via the Integration. And it seemed to work fine, till I realised that all of the Door / window contact II are not shown in Home Assistant. Does your integration not support them to date or am I missing something?

Thank you in advance for your help.

**Comment by AudiIT-max** [comment]
That would be very interesting for me as well. Have 5 Bosch window sensors II Plus and a window senor II.

At the moment I have them integrated in Apple Home and per sensor one automation to activate and one to deactivate a boolean helper from HomeAssistant. This is not ideal and functions such as the vibration sensor of the Plus models cannot really be integrated well in Apple Home anyway

Thank you for your help.

**Comment by tschamm** [comment]
This is basically a feature request for the 3rd party library. I don't own the window sensor II, so you can help here by posting the device's JSON data. For the Shutter Control I it looked as follows:
```
    {
        "@type": "device",
        "rootDeviceId": "64-xx",
        "id": "hdm:HomeMaticIP:xxx",
        "deviceServiceIds": [
            "ShutterContact",
            "BatteryLevel"
        ],
        "manufacturer": "BOSCH",
        "roomId": "hz_8",
        "deviceModel": "SWD",
        "serial": "xxx",
        "profile": "REGULAR_WINDOW",
        "name": "Dachfenster Schlafzimmer",
        "status": "AVAILABLE",
        "childDeviceIds": []
    },
```

**Comment by AudiIT-max** [comment]
This is the window sensor II:
{
            '@type': 'device'
            'rootDeviceId': '64-da-a0-11-9e-e5'
            'id': 'hdm:ZigBee:18fc26000002c65e'
            'deviceServiceIds': ['CommunicationQuality', 'ShutterContact', 'BatteryLevel', 'Bypass']
            'manufacturer': 'BOSCH'
            'roomId': 'hz_2'
            'deviceModel': 'SWD2'
            'serial': '18FC26000002C65E'
            'profile': 'GENERIC'
            'name': 'Tür'
            'status': 'AVAILABLE'
            'childDeviceIds': []
}

And this is the JSON Data for the window sensor II plus:
{
            '@type': 'device'
            'rootDeviceId': '64-da-a0-11-9e-e5'
            'id': 'hdm:ZigBee:18fc260000024551'
            'deviceServiceIds': ['CommunicationQuality', 'ShutterContact', 'BatteryLevel', 'Bypass', 'VibrationSensor']
            'manufacturer': 'BOSCH'
            'roomId': 'hz_4'
            'deviceModel': 'SWD2_PLUS'
            'serial': '18FC260000024551'
            'profile': 'REGULAR_WINDOW'
            'name': 'Fenster'
            'status': 'AVAILABLE'
            'childDeviceIds': []
}

**Comment by tschamm** [comment]
Thank you, that's the info I was looking for. Can you also post the JSON for the additional service `Bypass` of the device?

**Comment by AudiIT-max** [comment]
Hi,
I'm having trouble getting Postman to work on my end, but can't seem to get the Python command to get the JSON from the bypass. 
For the JSON over from above I could just use 
`print(session.api.get_devices())`
use.
Postman always just gives me the message for the same certificates as the python script:
`Error: write EPROTO 140338376010984:error:10000412:SSL      routines:OPENSSL_internal:SSLV3_ALERT_BAD_CERTIFICATE:../../third_party/boringssl/src/ssl/tls_record.cc:594:SSL alert number 42`

If I use `print(session.device('hdm:ZigBee:c4988600000ba177').device_service('bypass'))` in python I just become None as response.

**Comment by joostme** [comment]
The output from my sensor for the `Bypass` service:

```json
	{
		"@type": "DeviceServiceData",
		"id": "Bypass",
		"deviceId": "hdm:ZigBee:18fc260000011512",
		"state": {
			"@type": "bypassState",
			"state": "BYPASS_INACTIVE",
			"configuration": {
				"enabled": true,
				"timeout": 5,
				"infinite": false
			}
		},
		"path": "/devices/hdm:ZigBee:18fc260000011512/services/Bypass"
	}
```

When I double-click the button the state changes to `BYPASS_ACTIVE`.
`timeout` is the Timeout in minutes in which Bosch SHC ignores the state of the window for automations.
If I disable the timeout in the app, `infinite` will be `true`

Sadly the button does not seem to send any event when short or long-pressing it. In the App I can configure automations. But I don't receive any events when polling the API.

**Comment by tschamm** [comment]
@joostme you can test the pre-release 0.4.39, which brings support for the Bypass service. As I do not own a Shutter Contact II / II Plus, I cannot test if it's working correctly. It is currently limited to setting the state to active/inactive. You cannot change the timeout or infinite via Home Assistant.
Please report back if bypass works or if not. Thanks!

**Comment by Deniz66** [comment]
Hi @tschamm, will you also support click events for short and long press on the contact II / II Plus?

**Comment by tschamm** [comment]
@Deniz66 What do you mean? Should HASS fire an event in case the `Bypass` state changes from `BYPASS_INACTIVE` to `BYPASS_ACTIVE`? IMHO, this is not necessary, as you can watch for state changes of the Bypass switch. Please reopen, if necessary.

**Comment by idominiki** [comment]
Would be great if there is an event when pushing the Button on SWD2_PLUS
