### ISSUE TITLE
compatibility issue - Bosch light / shutter control II not detected

### ISSUE THREAD

**Issue by DFS-90** [tschamm/boschshc-hass#68]
Hi,

I use the HACS version of this plugin.
As I recently installed some "light / shutter control II" devices, I tried to integrate those into my Home Assistant setup.

Unfortunately, I wasn't able to detect my new devices.
Is this a known limitation / problem / incompatibility or am I doing something wrong?

Is there a possibility to integrate the "light / shutter control II" devices in the same way as their predecessor (which works flawlessly in my setup)?

Thanks in advance and best regards,
David

**Comment by tschamm** [comment]
This is basically a feature request for the 3rd party library. I don't own the light/shutter control II (yet), so you can help here by posting the device's JSON data. For the Shutter Control I it looked as follows:
```
    {
        "@type": "device",
        "rootDeviceId": "64-xx",
        "id": "hdm:HomeMaticIP:30xxx",
        "deviceServiceIds": [
            "ShutterControl"
        ],
        "manufacturer": "BOSCH",
        "roomId": "hz_3",
        "deviceModel": "BBL",
        "serial": "xxx",
        "profile": "GENERIC",
        "name": "Rollladen 2",
        "status": "AVAILABLE",
        "childDeviceIds": []
    },
```

**Comment by joostme** [comment]
I already created the PR for the boschshcpy lib: https://github.com/tschamm/boschshcpy/pull/16
But for completeness sake here is the output from the API

```json
{
    "@type": "device",
    "rootDeviceId": "64-da-a0-XX-XX-XX",
    "id": "hdm:ZigBee: 18fc2600000XXXXX",
    "deviceServiceIds": [
        "CommunicationQuality",
        "ShutterContact",
        "BatteryLevel",
        "Bypass"
    ],
    "manufacturer": "BOSCH",
    "roomId": "hz_7",
    "deviceModel": "SWD2",
    "serial": "18FC2600000XXXXX",
    "profile": "REGULAR_WINDOW",
    "name": "Fenster Bad",
    "status": "AVAILABLE",
    "childDeviceIds": []
}
```

**Comment by DFS-90** [comment]
> This is basically a feature request for the 3rd party library. I don't own the light/shutter control II (yet), so you can help here by posting the device's JSON data. For the Shutter Control I it looked as follows:
> 
> ```
>     {
>         "@type": "device",
>         "rootDeviceId": "64-xx",
>         "id": "hdm:HomeMaticIP:30xxx",
>         "deviceServiceIds": [
>             "ShutterControl"
>         ],
>         "manufacturer": "BOSCH",
>         "roomId": "hz_3",
>         "deviceModel": "BBL",
>         "serial": "xxx",
>         "profile": "GENERIC",
>         "name": "Rollladen 2",
>         "status": "AVAILABLE",
>         "childDeviceIds": []
>     },
> ```

Sorry for my delayed answer - I first had to find out how to use Postman and how to establish a secured connection to my Bosch Smart Home controller.

This is the Postman output for one of my shutter controls:

<html><body>


0 |  
-- | --
@type | "device"
rootDeviceId | "64-xx-xx-xx-xx-xx"
id | "hdm:ZigBee:dc8exxxxxxxxxxxx"
deviceServiceIds |  
0 | "ShutterControl"
1 | "CommunicationQuality"
2 | "PowerMeter"
3 | "ChildProtection"
4 | "SwitchConfiguration"
manufacturer | "BOSCH"
roomId | "hz_7"
deviceModel | "MICROMODULE_SHUTTER"
serial | "DC8EXXXXXXXXXXXX"
profile | "GENERIC"
name | "Rolllade (Gartenseite links)"
status | "AVAILABLE"
childDeviceIds | []


</body>
</html>

Thanks and best regards,
David

**Comment by joostme** [comment]
@DFS-90 yeah you're right. I accidentally commented on the wrong issue. My bad

**Comment by ceedee666** [comment]
I just created a pull request (https://github.com/tschamm/boschshcpy/pull/19) to add initial support for the Bosch light / shutter control II.

**Comment by DFS-90** [comment]
> I just created a pull request ([tschamm/boschshcpy#19](https://github.com/tschamm/boschshcpy/pull/19)) to add initial support for the Bosch light / shutter control II.

Already done - please see [include support for "Bosch light / shutter control II" (deviceModel: "MICROMODULE_SHUTTER")](https://github.com/tschamm/boschshcpy/pull/18/files) ;-)

**Comment by tschamm** [comment]
Thank you! The additional services `PowerMeter`, `ChildProtection` as well as `SwitchConfiguration` are not yet supported.
