### ISSUE TITLE
Upgrading component to newest version

### ISSUE THREAD

**Issue by mvalero** [tschamm/boschshc-hass#69]
Hello,

I was wondering how to upgrade the custom component to a newer version and saw that there is no information about that on the readme.

Is it possible to just follow the same steps as for the initial installation and replace the component code with its newest version? Or are there any things that must be taken into account?

Thx in advance

**Comment by tschamm** [comment]
Do you use HACS or have you installed it manually in the custom component directory? If you are using HACS, you can use the update mechanism provided there (https://hacs.xyz/docs/basic/updates/). Otherwise just replace the component code with the newest version.
