### ISSUE TITLE
include support for "Bosch light / shutter control II" (deviceModel: "MICROMODULE_LIGHT_CONTROL")

### ISSUE THREAD

**Issue by DFS-90** [tschamm/boschshc-hass#71]
Please see [include support for "Bosch light / shutter control II" (deviceModel: "MICROMODULE_LIGHT_CONTROL") #20 ](https://github.com/tschamm/boschshcpy/pull/20).

**Comment by tschamm** [comment]
Closed with [c394311](https://github.com/tschamm/boschshc-hass/commit/c39431197fb2794b9ef698a2292833d509fc4077)

**Comment by al308** [comment]
The shutter control II has two switches when used as a light control. The current master only recognizes the "second" switch. This in turn works fine (just fyi)
