### ISSUE TITLE
Bosch Thermostat II: service for valve control

### ISSUE THREAD

**Issue by erd82** [tschamm/boschshc-hass#72]
Hello, 

I am using the Bosch Thermostat II and this custom component (boschshc-hass) so that I can see the valve percentage.
Currently I can only control the valve by setting a target temperature in auto mode. And then I have to rely on the logic and accuracy that bosch offers.

But would it be possible to offer a service with this customer component where you can directly control the valve opening? Or instead of a service a direct input value controlling the valve would be also ok.

Cheers, red

**Comment by tschamm** [comment]
Hi @erd82,
the Thermostat can only be controlled via the `RoomClimateControl` service. Currently neither the Thermostat I nor the Thermostat II are supporting setting values directly. Actually I have never tried to control to set the valve position via the Thermostat directly. Support for setting Child protection, offset control and silent mode are not currently not supported via the component.

**Comment by tschamm** [comment]
Thermostat (I and II) do not support setting valve values directly - won't fix.

**Comment by erd82** [comment]
It's a pity that there is no direct control possible. But it's ok. Finally, an indirect control (over room climate) is also fine. Many thanks! Cheers
