### ISSUE TITLE
Room Thermostat II support (home base II already in the works?)

### ISSUE THREAD

**Issue by Olli0103** [tschamm/boschshc-hass#80]
Hi 

I have new room thermostat II which are not working with this integration. Is there anything planned here? Also I have the new BSH hub already here but I assume this does not work also, right? 

Thanks!

**Comment by tschamm** [comment]
Can you provide me a postman excerpt of the device?

**Comment by Olli0103** [comment]
Sure, can you tell how to get that?

**Comment by tschamm** [comment]
@Olli0103 it would be great if you can do a rawscan of the device and associated services, and paste the result here. For this, please follow the steps:
1. Install a python (>=3.10) environment on your computer
2. Install latest version of `boschshcpy`, you should have at least version 0.2.45
```pip install boschshcpy```
3. Register a new client
```boschshc_registerclient -ip _your_shc_ip_ -pw _your_shc_password_```
This will register your client and will write the associated certificate/key pair into your working directory.
4. Make a rawscan of your devices
```boschshc_rawscan -ip _your_shc_ip_ -cert _your_shc_cert_file_ -key _your_shc_key_file_ devices```
5. In the resulting json dump, you can look for the `device id` of your room thermostat II, copy this id and use it in the next step
6. Make a rawscan of the device
```boschshc_rawscan -ip _your_shc_ip_ -cert _your_shc_cert_file_ -key _your_shc_key_file_ device _your_device_id_```
Copy the output into the comment here, it will look somehow as follows
```
    {
        "@type": "device",
        "rootDeviceId": "xx-xx-xx-xx-xx-xx",
        "id": "hdm:HomeMaticIP:30xxx",
        "deviceServiceIds": [
            "Thermostat",
            "BatteryLevel",
            "ValveTappet",
            "SilentMode",
            "TemperatureLevel",
            "Linking",
            "TemperatureOffset"
        ],
        "manufacturer": "BOSCH",
        "roomId": "hz_8",
        "deviceModel": "TRV",
        "serial": "30xxx",
        "profile": "GENERIC",
        "name": "Test Thermostat",
        "status": "AVAILABLE",
        "parentDeviceId": "roomClimateControl_hz_8",
        "childDeviceIds": []
    },
```
7. Make a rawscan of the associated services of the device
```boschshc_rawscan -ip _your_shc_ip_ -cert _your_shc_cert_file_ -key _your_shc_key_file_ device_services _your_device_id_```
Copy the output also in here, it will look as the follows:
```
[
    {
        "@type": "DeviceServiceData",
        "id": "BatteryLevel",
        "deviceId": "hdm:HomeMaticIP:30xxx",
        "path": "/devices/hdm:HomeMaticIP:30xxx/services/BatteryLevel"
    },
    {
        "@type": "DeviceServiceData",
        "id": "Thermostat",
        "deviceId": "hdm:HomeMaticIP:30xxx",
        "state": {
            "@type": "childLockState",
            "childLock": "OFF"
        },
        "path": "/devices/hdm:HomeMaticIP:30xxx/services/Thermostat"
    },
...
]
```

**Comment by tschamm** [comment]
For the new homebase, I do not know what will change. I also do not own it, this can become more tricky...

**Comment by tschamm** [comment]
Can you test if your Thermostat is now supported, with version 0.4.44?
If not, please do a `rawscan` of your device and paste the output here. For additional info how to do a rawscan, see here: https://github.com/tschamm/boschshcpy#command-line-access-to-shc

**Comment by Olli0103** [comment]
Working flawlessly! Thanks
