### ISSUE TITLE
Ledvance Lamps not working

### ISSUE THREAD

**Issue by lesgrebe** [tschamm/boschshc-hass#82]
Hello!

Fist of all, thanks for supporting us with updates - good job!

With the latest Version 0.4.42, which I updated 1hour ago, the LEDVANCE Lamps not working any more. Message after updating to 0.4.42: Diese Entität wird nicht mehr von der Integration bosch_shc bereitgestellt. Wenn die Entität nicht mehr verwendet wird, lösche sie in den Einstellungen.

Maybe a fault on my side but did work before update.

Greetings
Michi

**Comment by tschamm** [comment]
I'll have a look.

**Comment by lesgrebe** [comment]
Merci, Danke dir!
