### ISSUE TITLE
Room Thermostat II Humidity not working

### ISSUE THREAD

**Issue by Thxlx** [tschamm/boschshc-hass#84]
Hi!

Everything works flawless in Home Assistant but the Humidity Sensor of the Room Thermostat II does not show any values.
<img width="617" alt="Screenshot 2023-02-06 at 12 59 30" src="https://user-images.githubusercontent.com/38328877/216966358-3d0e4294-ebf1-4ffc-a6bb-18d9e7937d66.png">

**Comment by tschamm** [comment]
What version is installed on your SHC? Is there any update available?

**Comment by Thxlx** [comment]
I am on 10.12.2785-28162 and there seems to be no update available

**Comment by tschamm** [comment]
Hm, can you post the `rawscan` results for the particular device? Missing the humidity level was observed [here](https://github.com/home-assistant/core/issues/85467#issuecomment-1409564897) also. What is the device code for your thermostat?

**Comment by Thxlx** [comment]
The rawsacn results show the humidity level... 

        "deviceServiceIds": [
            "CommunicationQuality",
            "Thermostat",
            "BatteryLevel",
            "DisplayConfiguration",
            "TemperatureLevel",
            "HumidityLevel",
            "TerminalConfiguration",
            "Linking",
            "TemperatureOffset"
        ],
        "manufacturer": "BOSCH",
        "roomId": "hz_1",
        "deviceModel": "RTH2_BAT",
        "serial": "xxxxxx",
        "profile": "GENERIC",
        "name": "Raumthermostat",
        "status": "AVAILABLE",
        "parentDeviceId": "roomClimateControl_hz_1",
        "childDeviceIds": []

**Comment by tschamm** [comment]
Ok, that looks strange to me. Can you check if the entity (see entity registry) has been created twice?

**Comment by Thxlx** [comment]
No, its only one.
I will migrate my Home Assistant to a new System today. Maybe theres something wrong on my site. I'll post an update here if something changes..

**Comment by tschamm** [comment]
I think I found the issue. The boschshcpy version was still missing the support for humidity level. My fault ...
Should be fixed in the current [release](https://github.com/tschamm/boschshc-hass/releases/tag/0.4.46)

**Comment by Thxlx** [comment]
Yep! Works perfectly fine! Thank you!
