### ISSUE TITLE
Bosch "Universalschalter Flex" not supported

### ISSUE THREAD

**Issue by derpate1989** [tschamm/boschshc-hass#85]
Hey, it is possible to integrat the "universalschalter flex" in your  Integration? Its a normal switch with 2 Buttons.

The integration detect him but can not display any switchs.

![image](https://user-images.githubusercontent.com/93314730/217215798-7bae8815-6e78-4093-ba09-c63f491cea04.jpeg)

**Comment by tschamm** [comment]
It is already integrated. If you press a button, an event is triggered. Check the logbook entries.

**Comment by derpate1989** [comment]
I press both buttons but an event is not written to the logbook.

**Comment by dolodobendan** [comment]
No problems here. Do you use a current version of the integration?

**Comment by tschamm** [comment]
The initial process is quite strange. After a restart of the SHC, press a button of the Switch first, then do a restart of Home Assistant. After that it works for me.

**Comment by tschamm** [comment]
Can you provide a short comment if it is working now?

**Comment by derpate1989** [comment]
Sorry for the late response. Yes it work Fine After restart of SHC and Home Assistant. Thanks a lot!

**Comment by tschamm** [comment]
I have no clue why events are only registered correctly after a restart of HA. I'm closing it for now.
