### ISSUE TITLE
Support missing for MICROMODULE_BLINDS device 

### ISSUE THREAD

**Issue by olsen-sorensen** [tschamm/boschshc-hass#86]
Hi there, is there something ongoing already to support the version two of the shutter/switch (in wall)?

https://www.bosch-smarthome.com/at/de/produkte/geraete/licht-rollladensteuerung/

**Comment by olsen-sorensen** [comment]
I cant see any device/entity...

**Comment by tschamm** [comment]
Are you using the official integration or the custom component? Only the custom component brings the support for the SwitchII.

**Comment by olsen-sorensen** [comment]
Custom component installed via hacs, current version: 0.4.45

**Comment by tschamm** [comment]
I actually integrated the device already, see https://github.com/tschamm/boschshc-hass/issues/68

Can you post a `rawscan` of the device (see https://github.com/tschamm/boschshc-hass/issues/80#issuecomment-1399595977)

**Comment by olsen-sorensen** [comment]
{
        "@type": "device",
        "rootDeviceId": "64-da-a0-10-c3-9c",
        "id": "hdm:ZigBee:f4b3b1fffe106c2a",
        "deviceServiceIds": [
            "PowerMeter",
            "ShutterControl",
            "CommunicationQuality",
            "ChildProtection",
            "BlindsControl",
            "SwitchConfiguration",
            "BlindsSceneControl"
        ],
        "manufacturer": "BOSCH",
        "roomId": "hz_1",
        "deviceModel": "MICROMODULE_BLINDS",
        "serial": "F4B3B1FFFE106C2A",
        "profile": "GENERIC",
        "name": "Rollladensteuerung",
        "status": "AVAILABLE",
        "childDeviceIds": []
    },

**Comment by olsen-sorensen** [comment]
`[
    {
        "@type": "DeviceServiceData",
        "id": "BlindsControl",
        "deviceId": "hdm:ZigBee:f4b3b1fffe106c2a",
        "state": {
            "@type": "blindsControlState",
            "targetAngle": 0.0,
            "currentAngle": 0.0,
            "blindsType": "DEGREE_180",
            "bladeAdjustmentTimeInMillis": 1000
        },
        "operations": [
            "decrementAngle",
            "incrementAngle"
        ],
        "path": "/devices/hdm:ZigBee:f4b3b1fffe106c2a/services/BlindsControl"
    },
    {
        "@type": "DeviceServiceData",
        "id": "SwitchConfiguration",
        "deviceId": "hdm:ZigBee:f4b3b1fffe106c2a",
        "state": {
            "@type": "SwitchConfigurationState",
            "switchType": "PUSHBUTTON",
            "swapInputs": false
        },
        "path": "/devices/hdm:ZigBee:f4b3b1fffe106c2a/services/SwitchConfiguration"
    },
    {
        "@type": "DeviceServiceData",
        "id": "ChildProtection",
        "deviceId": "hdm:ZigBee:f4b3b1fffe106c2a",
        "state": {
            "@type": "ChildProtectionState",
            "childLockActive": false
        },
        "path": "/devices/hdm:ZigBee:f4b3b1fffe106c2a/services/ChildProtection"
    },
    {
        "@type": "DeviceServiceData",
        "id": "PowerMeter",
        "deviceId": "hdm:ZigBee:f4b3b1fffe106c2a",
        "state": {
            "@type": "powerMeterState",
            "powerConsumption": 0.0,
            "energyConsumption": 1700.0
        },
        "path": "/devices/hdm:ZigBee:f4b3b1fffe106c2a/services/PowerMeter"
    },
    {
        "@type": "DeviceServiceData",
        "id": "ShutterControl",
        "deviceId": "hdm:ZigBee:f4b3b1fffe106c2a",
        "state": {
            "@type": "shutterControlState",
            "calibrated": true,
            "referenceMovingTimes": {
                "movingTimeTopToBottomInMillis": 60900,
                "movingTimeBottomToTopInMillis": 62500
            },
            "level": 0.0,
            "operationState": "STOPPED",
            "endPositionAutoDetect": true,
            "endPositionSupported": true,
            "delayCompensationTime": 0.0,
            "delayCompensationSupported": true,
            "automaticDelayCompensation": false
        },
        "operations": [
            "decrementOpenLevel",
            "incrementOpenLevel"
        ],
        "path": "/devices/hdm:ZigBee:f4b3b1fffe106c2a/services/ShutterControl"
    },
    {
        "@type": "DeviceServiceData",
        "id": "CommunicationQuality",
        "deviceId": "hdm:ZigBee:f4b3b1fffe106c2a",
        "state": {
            "@type": "communicationQualityState",
            "quality": "UNKNOWN"
        },
        "path": "/devices/hdm:ZigBee:f4b3b1fffe106c2a/services/CommunicationQuality"
    },
    {
        "@type": "DeviceServiceData",
        "id": "BlindsSceneControl",
        "deviceId": "hdm:ZigBee:f4b3b1fffe106c2a",
        "state": {
            "@type": "blindsSceneControlState",
            "level": 0.0,
            "angle": 0.0
        },
        "path": "/devices/hdm:ZigBee:f4b3b1fffe106c2a/services/BlindsSceneControl"
    }
]`

**Comment by tschamm** [comment]
Ok, thanks. It seems you are using the device for blinds control, not for shutter control, as you have configured it so. Until now, support is just given for shutters. I think it's not hard to implement, but so at least we know the reason for the missing device.

**Comment by olsen-sorensen** [comment]
Im wondering it identifies as a blind because i use it as a shutter (i might have misunderstood that, in german its a "raffstore") and thats what i can see in the original bosch controller app too.

**Comment by tschamm** [comment]
As far as I know, Shutter control is meant for "Rollladen" (up / down control), while blind is for "Jalousie/Lamellen" (control up/down as well as control the angle of the blind).

**Comment by olsen-sorensen** [comment]
Google says youre right :) Thanks for clarification and your help.

**Comment by tschamm** [comment]
Fixed by [4f7a1bd](https://github.com/tschamm/boschshc-hass/commit/4f7a1bd3246cb8f23470aaab7e0edb9271ca3533)

I'll added support for blinds control. Control is currently only for opening and closing the shutter, not yet for control of the angle / tilt value (`target_angle`). For this I need a more info on the API semantics. What is the range to set the tilt? Is 0 open or closed? 
If you want to provide more data on this, feel free to reopen and add the additional info.
