### ISSUE TITLE
Two idea as suggestion

### ISSUE THREAD

**Issue by derpate1989** [tschamm/boschshc-hass#88]
Hello,

Is it possible to add the motion detector of the camera as a sensor?

And

Could you integrate scenarios from the Bosch app as a sensor with scenario triggered ON / OFF. So you could use the twist and the cameras as well. As soon as they trigger something, the "scenario sensor" switches briefly to ON and immediately back to OFF. This can be used well in Home Assistant.

**Comment by tschamm** [comment]
The motion detector of Camera Eyes is not reported via the API. If you can find a way how to access the state change, let me know. 

When a scenario is triggered, HA fires an event. You can listen to that event in your automation.

**Comment by derpate1989** [comment]
Ok thanks for the quick answer. Under which device or in which entitity can I find the fire event.

**Comment by tschamm** [comment]
You can find the fire event by listening to the `bosch_shc.event` messages. For testing, go to `Developer`-`Events` page.

**Comment by derpate1989** [comment]
I have found it. The automation works great. I use the motion detector of the Bosch camera and trigger a scenario without content. But the trigger is usable with iobroker and Home Assistant through it.

Thanks a lot!
