### ISSUE TITLE
Tür-/Fensterkontakt II integrierten Button ohne Funktion

### ISSUE THREAD

**Issue by matzidp8** [tschamm/boschshc-hass#89]
Hallo,

ich habe heute zwei SWD2 installiert. Im HA sind alle Entitäten vorhanden. 

1. Binary Sensor Batterie
2. Binary Sensor geöffnet/geschlossen
3. Switch für den Button 

![Türkontakt Geräte](https://user-images.githubusercontent.com/126620934/222515941-28b41e91-abc7-40b9-ad84-484e737d18fc.JPG)

![Türkontakt Entitäten](https://user-images.githubusercontent.com/126620934/222515947-f51c8dd0-1dc3-4209-9bfe-5b903eb30adb.JPG)

Aber wenn ich den Button am Türkontakt drücke, egal ob kurz oder lang kommt es nicht im HA an.
Auch im Log ist nichts vorhanden.

In der Bosch App habe ich zum testen mal eine Automation erstellt, **WENN** Button kurz gedrückt wird **DANN** sende Push Nachricht, dies funktioniert.

Komischerweise taucht der Button am Türkontakt auch als Schalter im HA auf.
Bei den Batterie Lichtschalter wie den WRC2 gibt es nur die Entität Batterie.
Und die Schaltfunktion ist in einer Automation auswählbar.

Habe ich da was übersehen, ich möchte eine Automation erstellen, wenn der Button gedrückt wird, dann schalte einen Switch.

Gruß
Matthias

**Comment by tschamm** [comment]
Das ist leider richtig, der Schalter ist nicht in HA integriert. Hierzu benötige ich das JSON, welches bei einem Push Event erzeugt wird. Ein Beispiel, wie du das erzeugen kannst, lasse ich dir die nächsten Tage zukommen.

**Comment by matzidp8** [comment]
Hallo tschamm,

denkst du bitte bei Gelegnheit an die Erklärung wie ich Dir die erforderlichen Daten zukommen lassen kann.

Gruß
Matthias

**Comment by renspr** [comment]
> Das ist leider richtig, der Schalter ist nicht in HA integriert. Hierzu benötige ich das JSON, welches bei einem Push Event erzeugt wird. Ein Beispiel, wie du das erzeugen kannst, lasse ich dir die nächsten Tage zukommen.

Ich wäre an dem Feature auch interessiert. Wenn Du einen Hinweis gibst, wie ich das JSON abfragen kann, würde ich es schicken.

**Comment by tschamm** [comment]
Hi, can you do a rawscan of the device and the device services, here is a description: https://github.com/tschamm/boschshcpy#rawscans

**Comment by matzidp8** [comment]
Hallo,
Oh ok gerne. Leider verstehe ich nicht ganz wie ich dies machen kann.
Könntest du dies bitte genauer erklären.
GrußMatthias


    Am Samstag, 4. November 2023 um 21:34:21 MEZ hat Thomas Schamm ***@***.***> Folgendes geschrieben:  
 
 


Hi, can you do a rawscan of the device and the device services, here is a description: https://github.com/tschamm/boschshcpy#rawscans

**Comment by tschamm** [comment]
Should be available when implemented #78

**Comment by tschamm** [comment]
Can you describe a bit more on the bypass what is working and what not. I understand if you press the bypass on the shutter contact, the bypass switch is not changing in HA. What happens other way around, if you turn on the switch in HA, do you see anything in the official Bosch App or on the device itself?

**Comment by tschamm** [comment]
Found the potential error for bypass, too bad if testing is not possible without owning the devices... Version 0.4.65 should work.

**Comment by matzidp8** [comment]
Super Danke Dir.

Wie kann ich auf Version 0.4.65 updaten.
Wenn ich in HACS-Integrationen-Bosch... gehe zeigt es an das ich die Version 0.4.63 habe.

Ich finde aber nichts um auf die neue Version zu kommen.

Wenn ich auf erneut heruntergeladen klicke, kann ich auch nur die Version 0.4.63 auswählen.
![Screenshot_20231106_084357_Home Assistant](https://github.com/tschamm/boschshc-hass/assets/126620934/3e7c20a4-694b-4205-8677-e91bcda6b5e1)

**Comment by tschamm** [comment]
Richtig, ich habe kein Release für die Version erstellt. Wenn du `master` wählst, bekommst du den aktuellsten Stand.

**Comment by matzidp8** [comment]
Jetzt habe ich erstmal ein VollBackup vom HA von gestern wieder aufgespielt.
Und warte auf deine Antwort, keine Ahnung habe ich was falsch gemacht?

Du kannst auch gerne bei mir per Teamviewer zugreifen wenn es Dir hilft. Schreibe einfach per PN

**Comment by tschamm** [comment]
My sensor has arrived, and I found a bug which prevented to `binary sensor` platform to load correctly. Bypass is now available. However, pressing the button short/long is not published via the Bosch API, so that event cannot be captured.
Fixed in commit e7f98da.

**Comment by matzidp8** [comment]
Danke Dir für die Rückmeldung und die super Integration.

Leider habe ich mit der Version  0.4.70 und 0.4.71 folgendes Problem.
Wenn ich die Bosch Integration manuell neu lade, gehen alle Geräte bzw. die Entitäten offline.

Wenn ich sie dann nochmals neu laden will kommt folgende Fehlermeldung.

![Screenshot_20231205_070821_Home Assistant](https://github.com/tschamm/boschshc-hass/assets/126620934/dbd0fc3d-ecaa-4697-8087-d890e1aa2e21)

Aufgefallen ist mir dies weil ich eine Automation habe, die früh um 07:00 Uhr zwei Geräte der Bosch Integration neu lädt, weil ab und zu die Geräte offline waren.  Und dann alle Geräte offline wahren.

![Automation Bosch Integration neu laden](https://github.com/tschamm/boschshc-hass/assets/126620934/4450ff3a-6ea0-4fce-9c6e-a68b6ef403a5)

Mit der Version 0.4.63 funktioniert es.

**Comment by tschamm** [comment]
Bitte mache ein neues Issue, und schicke noch ein Auszug der Log Datei, wo der Fehler auftritt.

**Comment by matzidp8** [comment]
Alles klar mache ich später.

Wie kann ich Dir das Log als PN schicken, finde leider keine Möglichkeit?
Am besten du schreibst mir per PN und ich antworte.
