### ISSUE TITLE
Adjusting light color for RGBA-Lightstripe

### ISSUE THREAD

**Issue by wsirhc** [tschamm/boschshc-hass#9]
So now that I've got a ledvance RGBA-Lightstripe, I'd like to adjust the Light-Color.

Here some device details as json-output from postman:
```
{
        "@type": "device",
        "rootDeviceId": "ff-ff-ff-ff-ff-ff",
        "id": "hdm:ZigBee:ffffffffffffffff",
        "deviceServiceIds": [
            "CommunicationQuality",
            "MultiLevelSwitch",
            "HSBColorActuator",
            "BinarySwitch"
        ],
        "manufacturer": "LEDVANCE",
        "roomId": "hz_2",
        "deviceModel": "LEDVANCE_LIGHT",
        "serial": "FFFFFFFFFFFFFFFF",
        "profile": "GENERIC",
        "iconId": "icon_ledvance_light_strip",
        "name": "Farbstreifen",
        "status": "AVAILABLE",
        "childDeviceIds": []
    },
```

Services for this device:
```
[
    {
        "@type": "DeviceServiceData",
        "id": "MultiLevelSwitch",
        "deviceId": "hdm:ZigBee:f0d1b80000157e90",
        "state": {
            "@type": "multiLevelSwitchState",
            "level": 100
        },
        "path": "/devices/hdm:ZigBee:f0d1b80000157e90/services/MultiLevelSwitch"
    },
    {
        "@type": "DeviceServiceData",
        "id": "HSBColorActuator",
        "deviceId": "hdm:ZigBee:f0d1b80000157e90",
        "state": {
            "@type": "colorState",
            "rgb": -12427,
            "gamut": "LEDVANCE_GAMUT_A",
            "colorTemperatureRange": {
                "minCt": 153,
                "maxCt": 526
            }
        },
        "path": "/devices/hdm:ZigBee:f0d1b80000157e90/services/HSBColorActuator"
    },
    {
        "@type": "DeviceServiceData",
        "id": "BinarySwitch",
        "deviceId": "hdm:ZigBee:f0d1b80000157e90",
        "state": {
            "@type": "binarySwitchState",
            "on": true
        },
        "path": "/devices/hdm:ZigBee:f0d1b80000157e90/services/BinarySwitch"
    },
    {
        "@type": "DeviceServiceData",
        "id": "CommunicationQuality",
        "deviceId": "hdm:ZigBee:f0d1b80000157e90",
        "state": {
            "@type": "communicationQualityState",
            "quality": "GOOD"
        },
        "path": "/devices/hdm:ZigBee:f0d1b80000157e90/services/CommunicationQuality"
    }
]
```

**Comment by tschamm** [comment]
I don't understand the meaning of the provided rgb color value. It is neither a color temperature (as provided by hue lights) nor some senseful hex value, which could be interpreted as 0xAARRGGBB. However, I'm not very familiar with this kind of problem.
Can you set your light to some defined colors using the Bosch App and report the rgb values? Perhaps this can help to interpret the meaning of the rgb value. I would suggest
* blue only w/ max brightness
* blue only w/ lowest brightness
* green only w/ max brightness
* green only w/ lowest brightness
* red only w/ max brightness
* red only w/ lowest brightness

**Comment by wsirhc** [comment]
OK what I've found out is that color is set by,   
```
 "@type": "colorState",
 "rgb": decimal color value of hex-equivalent
```
So the rgb-value is the decimal equivalent of the Hex-Color-Code.
Red (255,0,0) --> #FF0000 --> 16711680         
Green (0,255,0) --> #00FF00 --> 65280     
Blue (0,0,255) --> #0000FF --> 255

I managed to set color with this curl:
```
curl --location --request PUT 'https://192.168.1.2:8444/smarthome/devices/hdm:ZigBee:xxxxxxxxxxxxxxxx/services/HSBColorActuator/state' \
--header 'Content-Type: application/json' \
--header 'api-version: 1.0' \
--data-raw '{
    "@type": "colorState",
    "rgb": 65280
}'
```
Regardless of what brightness I did set, it has no impact to the rgb-value.

**Comment by tschamm** [comment]
Can you try https://github.com/tschamm/boschshc-hass/commit/142abdf5f4c64ff5b571a2754db512d5b078ca46 if this works for your colored ledvance lights?

**Comment by wsirhc** [comment]
Works like charm! Thanks for the xmas present :)

<p>
<img width=250px src="https://user-images.githubusercontent.com/20781198/102587907-e6a63f80-410c-11eb-92a7-359c765c568f.png">
<img width=250px src="https://user-images.githubusercontent.com/20781198/102587915-e8700300-410c-11eb-9df4-6df0ad6df347.jpg">
</p>
<br>
<p>
<img width=250px src="https://user-images.githubusercontent.com/20781198/102587911-e73ed600-410c-11eb-9a48-d3e465c9c13e.png">
<img width=250px src="https://user-images.githubusercontent.com/20781198/102587920-e9089980-410c-11eb-8222-3144dea4dc23.jpg">
</p>

<p>
<img width=250px src="https://user-images.githubusercontent.com/20781198/102587913-e7d76c80-410c-11eb-8d12-d52ec714e801.png">
<img width=250px src="https://user-images.githubusercontent.com/20781198/102587922-e9a13000-410c-11eb-8053-c2e8c58a0c5f.jpg">
</p>
