### ISSUE TITLE
Device Cleanup - removed Devices still displayed

### ISSUE THREAD

**Issue by ghostridernrw40** [tschamm/boschshc-hass#90]
![image](https://user-images.githubusercontent.com/117640399/223350645-e0316f7a-4a20-4fc2-93c6-e7fdbc370806.png)

Hi,

I removed my 5 twinguards on the Bosch Bridge, but three twinguards are still displayed. Restarting the Bosch Bridge etc. did not help, how can these devices be cleaned up without completely reinstalling the integration?

**Comment by tschamm** [comment]
Normally they should disappear when being deleted in the Bosch app. If not, you can either disable the devices, or remove them manually in the `.storage/core.device_registry` and `.storage/core.entity_registry`.
