### ISSUE TITLE
Error while loading integration (ConfigEntries / async_setup_platforms)

### ISSUE THREAD

**Issue by KlimekDE** [tschamm/boschshc-hass#93]
Dear Developers,

today this morning the controller come unavailable and I had to reboot it multiple times. The official Bosch Smart Home App (Android) is available to reach the controller again, no update has been installed on the controller itself (no update information appeared). After checking HA I noticed that the SHC integration fails to start with attached error message.

Can you help me? What kind of information do need from my side for further debugging this issue? Thank you for any help!

Logger: homeassistant.config_entries
Source: custom_components/bosch_shc/__init__.py:89
Integration: Bosch SHC (documentation, issues)
First occurred: 09:59:48 (3 occurrences)
Last logged: 10:01:37

Error setting up entry Bosch Smart Home for bosch_shc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/bosch_shc/__init__.py", line 89, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by ValendurMeles** [comment]
Got an error identical to KlimekDE. Problem remains after 2023.5.1 update.

**Comment by epichb** [comment]
Probably related to https://github.com/home-assistant/core/pull/91929 (included in [Update 2023.5](https://www.home-assistant.io/changelogs/core-2023.5)). There is a [recommended replacement](https://developers.home-assistant.io/blog/2022/07/08/config_entry_forwards/) for the call.

**Comment by epichb** [comment]
After taking a look at the relevant code I realized that the issue does not occur with the most recent version of the integration. Anyone with the issue (including me) just needs to upgrade to the most recent version.

**Comment by KlimekDE** [comment]
@epichb Thanks for your investigation into the code itself. After updating to the lastest version the problem got solved and devices are again controlable via HA. Does anyone has an good method to keep the bosch_shc up2date? Currently I'am downloading the master.zip itself, unzipping it and then copying the relavant content to the custom_component directory. Is there an "auto-update" somehow possible?

**Comment by ValendurMeles** [comment]
Thank you epichb for checking. Always wanted to make a cleanup, so I used the chance. 
Working like a charm againg. Kudos!

**Comment by tschamm** [comment]
You can use HACS for this, there you will be able to update the component just via some clicks.
Otherwise, you can download the latest release from https://github.com/tschamm/boschshc-hass/releases
These are tested and should be fine to use.
