### ISSUE TITLE
'ConfigEntries' object has no attribute 'async_setup_platforms'

### ISSUE THREAD

**Issue by androidwannabe** [tschamm/boschshc-hass#96]
Hey,

after updating to Home Assistant 2023.5.3 yesterday, I received the following error this morning:

![grafik](https://github.com/tschamm/boschshc-hass/assets/84272776/7b1754e1-4f75-466b-ab90-d64471e1980a)

```
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/bosch_shc/__init__.py:89
Integration: Bosch SHC (documentation, issues)
First occurred: 03:03:42 (2 occurrences)
Last logged: 08:59:03

Error setting up entry shc038c69 for bosch_shc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/bosch_shc/__init__.py", line 89, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

```

Should I go back to 2023.4.0 or is this maybe a known error and somebody already knows how to fix it?

**Comment by armin-gh** [comment]
hi
the latest version available here (0.4.50) should have fixed this, running 2023.5.2 without problems in the Bosch SHC custom component.

Armin

**Comment by androidwannabe** [comment]
Hi,
thanks! I updated the custom component and now it works. 

How would I ideally update this custom component? I just downloaded the folder again and copied it to HA. After that, all the room climate entities got replaced by room_climate_xy_**2** and I had to reassign a few things in node red. I couldnt find it in HACS, thats where I update the node red custom component, for instance.

**Comment by armin-gh** [comment]
Depends on how you install it, by copying manually into the custom_components folder or via HACS?
it is in HACS: 
![image](https://github.com/tschamm/boschshc-hass/assets/71582770/af134668-6407-40c3-8c7f-802f0c442d17)

I initially installed it manully and update it manually the way you did it, at the time, if I remember correctly, the integration was not available in HACS. Never had an issue with duplicated entities.
I'm running HA Core in a Python VENV and stop the HA service before copying the files, not sure how you can stop when using different installation methods for HA

Armin

**Comment by androidwannabe** [comment]
Thanks again. I first copied the contents of the custom component manually. At this point I didn't even know about HACS.
I have it now set up via HACS, so I'll get all the updates in the future and won't have to aka unnecessary questions. Thank you for taking the time to answer.

**Comment by MatejBalantic** [comment]
Hi, I've hit exact same issue and upgrading help.

Unfortunately also for me upgrading caused all room climate entities to become duplicated (the duplicated entity haveing a `_2` suffix). You can't delete the old entity, because it's still connected to the integration

**Comment by tschamm** [comment]
The integration did. a rewrite of the unique ids, probably this was not backwards compatible for really old versions. Sorry for that. 
You can manually edit the entity registry,  delete both duplicate entries (the old entry and the new entry) and restart HA. This should fix it. 
Again, sorry for that.
