### ISSUE TITLE
Integrate new product

### ISSUE THREAD

**Issue by derpate1989** [tschamm/boschshc-hass#97]
Is it possible to include the new hardware "Light/Shutter control 2" in the integration?

Link ->
https://www.bosch-smarthome.com/de/de/produkte/geraete/licht-rollladensteuerung/

**Comment by tschamm** [comment]
What's exactly what you are missing? The control is already included.

**Comment by derpate1989** [comment]
Ok. I can not see the new shutter control 2 despite reloading the integration and restarting Home Assistant

**Comment by derpate1989** [comment]
I think I have found the problem. 

I have configured it as a shutter control (in Germany we say Markise). The control is not displayed to me even with Alexa.

**Comment by tschamm** [comment]
Can you post the device info for a device configured as awning / Markise? You can use postman or the rawscan functionality: https://github.com/tschamm/boschshcpy#rawscans

**Comment by alexwide** [comment]
I have the exact same Problem. 

Here is the output from my controller

    {
        "@type": "device",
        "rootDeviceId": "64-da-a0-03-97-7c",
        "id": "hdm:ZigBee:e0798dfffe633c65",
        "deviceServiceIds": [
            "PowerMeter",
            "ShutterControl",
            "CommunicationQuality",
            "ChildProtection",
            "SwitchConfiguration"
        ],
        "manufacturer": "BOSCH",
        "roomId": "hz_4",
        "deviceModel": "MICROMODULE_AWNING",
        "serial": "E0798DFFFE633C65",
        "profile": "GENERIC",
        "name": "Markise",
        "status": "AVAILABLE",
        "childDeviceIds": []
    }

**Comment by tschamm** [comment]
Added support for awning in the latest commit f16e8c9
