### ISSUE TITLE
Integrate new product Bosch Universalschalter II

### ISSUE THREAD

**Issue by Starcon79** [tschamm/boschshc-hass#99]
Is it possible to include the new hardware "Universalschalter 2" in the integration?  I added it to my controller and restarted the integration but I don't see the device. 

Link: [https://www.bosch-smarthome.com/de/de/produkte/bedienelemente-und-zubehoer/universalschalter/?gad=1&gclid=Cj0KCQjw1_SkBhDwARIsANbGpFuvbS5hVZSOHCKzD2qn9a6L0z_lJTiwbU6MTLVRKgJL-qFhGgYs_egaAi2MEALw_wcB](url)

**Comment by tschamm** [comment]
Can you do a rawscan and report the details of the device here, then I can add it.

**Comment by Starcon79** [comment]
I'll try it. Haven't done anything like this before. If there is a video tutorial then it is easier to understand.

**Comment by glumanda** [comment]
i use the twist and the "Universalschalter 2" without an integration in HA. For each function i define a scenario in bsh app without any action. Then i use this scenario as an automation  trigger like in the following code snippet:

    trigger:
      - platform: event
        event_type:  bosch_shc.event
        event_data:
            event_type: SCENARIO
            event_subtype: 'Hecke bewassern'

German Umlaute are mapped to corresponding "simple" letter. I hope it helps.

**Comment by COLT9001** [comment]
Here once the rawscan

```
    {
        "@type": "device",
        "rootDeviceId": "64-da-a0-xx-xx-xx",
        "id": "hdm:ZigBee:001e5e0902xxxxxx",
        "deviceServiceIds": [
            "CommunicationQuality",
            "BatteryLevel",
            "Keypad"
        ],
        "manufacturer": "BOSCH",
        "roomId": "hz_6",
        "deviceModel": "SWITCH2",
        "serial": "001E5E0902xxxxxx",
        "profile": "GENERIC",
        "name": "SchalterCouch",
        "status": "AVAILABLE",
        "childDeviceIds": [],
        "supportedProfiles": []
    },
```

Here the manual to create a rawscan
https://github.com/tschamm/boschshcpy#command-line-access-to-shc

**Comment by hkohls** [comment]
I am using this configuration, here is an extract from the rawscan. If you need more, just let me know!

 { 

        "@type": "device", 
        "rootDeviceId": "64-da-a0-40-5d-7b", 
        "id": "hdm:ZigBee:287681fffe705763", 
        "deviceServiceIds": [ 
            "CommunicationQuality", 
            "ImpulseSwitch", 
            "ChildProtection", 
            "ElectricalFaults" 
        ], 
        "manufacturer": "BOSCH", 
        "roomId": "hz_1", 
        "deviceModel": "MICROMODULE_RELAY", 
        "serial": "287681FFFE705763", 
        "profile": "GENERIC", 
        "iconId": "ip_garage", 
        "name": "Garagentor", 
        "status": "AVAILABLE", 
        "childDeviceIds": [], 
        "supportedProfiles": [] 
    }, 
==================================
[ 
    { 
        "@type": "DeviceServiceData", 
        "id": "ImpulseSwitch", 
        "deviceId": "hdm:ZigBee:287681fffe705763", 
        "state": { 
            "@type": "ImpulseSwitchState", 
            "impulseState": false, 
            "impulseLength": 10, 
            "instantOfLastImpulse": "2023-08-12T17:04:08.569170Z" 
        }, 
        "path": "/devices/hdm:ZigBee:287681fffe705763/services/ImpulseSwitch" 
    }, 
    { 
        "@type": "DeviceServiceData", 
        "id": "CommunicationQuality", 
        "deviceId": "hdm:ZigBee:287681fffe705763", 
        "state": { 
            "@type": "communicationQualityState", 
            "quality": "GOOD" 
        }, 
        "path": "/devices/hdm:ZigBee:287681fffe705763/services/CommunicationQuality" 
    }, 
    { 
        "@type": "DeviceServiceData", 
        "id": "ChildProtection", 
        "deviceId": "hdm:ZigBee:287681fffe705763", 
        "state": { 
            "@type": "ChildProtectionState", 
            "childLockActive": true 
        }, 
        "path": "/devices/hdm:ZigBee:287681fffe705763/services/ChildProtection" 
    }, 
    { 
        "@type": "DeviceServiceData", 
        "id": "ElectricalFaults", 
        "deviceId": "hdm:ZigBee:287681fffe705763", 
        "path": "/devices/hdm:ZigBee:287681fffe705763/services/ElectricalFaults" 
    } 
]

**Comment by COLT9001** [comment]
Tested the universal switch. Unfortunately, only the battery is displayed as entity. The keystroke is unfortunately missing.

**Comment by tschamm** [comment]
That’s correct. Create an automation and listen to events coming from the device, these should be available. 
 HA has added the event entity just this month and I have not found the time to update the component.

**Comment by COLT9001** [comment]
Hm, ok. Create a automation with trigger or event is also not possible. No key events or trigger can be found.....

**Comment by dolodobendan** [comment]
I don't see any new event entities for Bosch either, just for my hue switches.

**Comment by AlexW75** [comment]
Same Problem here … can’t find a way to get the button press.

**Comment by tschamm** [comment]
see also #112

**Comment by COLT9001** [comment]
Always the same... Only Battery is shown. No Button klick or anything else is visible for SWITCH2

**Comment by AlexW75** [comment]
I have the buttons now working by listening to the events the button fires.

**Comment by tschamm** [comment]
That are good news! If something is missing, please reopen the issue.
